/**
 * portfolio-architecture-pdf.ts — Executive Portfolio Architecture Blueprint PDF Generator
 *
 * Generates an executive-grade, beautifully styled PDF document containing:
 *  1. Executive Title Block & Strategic Context
 *  2. Section 01: Funnel Strategy & Archetype Thesis
 *  3. Section 02: 5-Dimension Portfolio Conversion Audit Scorecard
 *  4. Section 03: Section-by-Section Copy & Visual Layout Specifications
 *  5. Section 04: Designer & Engineering Handoff Directives
 *  6. Multi-page pagination, running headers, and footers
 */

import jsPDF from 'jspdf';
import type { PortfolioBlueprintSection } from '@/src/data/module3/authority-suite-engine';
import type { PortfolioConversionAudit, PortfolioArchetype } from './portfolio-architecture-engine';

export interface PortfolioArchitecturePdfData {
  userName: string;
  positioningHeadline: string;
  uniqueMechanism: string;
  serviceId: string | null;
  marketId: string | null;
  archetype: PortfolioArchetype | null;
  auditScore: PortfolioConversionAudit;
  sections: PortfolioBlueprintSection[];
}

/* ── Layout Constants (A4 in mm) ── */
const PW = 210;
const PH = 297;
const M = 16;
const CW = PW - M * 2; // 178 mm
const FOOTER_TOP = 284;
const SAFE = FOOTER_TOP - 8;

/* ── Color Palette ── */
const C = {
  navyDark: '#061b4f',
  navySlate: '#0b1c30',
  cobalt: '#0058be',
  cobaltLight: '#e8f1fd',
  indigo: '#4f46e5',
  indigoLight: '#eef2ff',
  emerald: '#059669',
  emeraldLight: '#ecfdf5',
  cardBg: '#ffffff',
  pageBg: '#f8fafc',
  border: '#e2e8f0',
  borderDark: '#cbd5e1',
  textMain: '#0f172a',
  textBody: '#334155',
  textMuted: '#64748b',
};

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace('#', ''), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

export function generatePortfolioArchitecturePdf(data: PortfolioArchitecturePdfData): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  let pageNum = 1;
  let y = M;

  const setFill = (hex: string) => doc.setFillColor(...hexToRgb(hex));
  const setStroke = (hex: string) => doc.setDrawColor(...hexToRgb(hex));
  const setText = (hex: string) => doc.setTextColor(...hexToRgb(hex));

  const addPage = () => {
    drawFooter();
    doc.addPage();
    pageNum++;
    y = M;
    drawRunningHeader();
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > SAFE) {
      addPage();
    }
  };

  const drawRunningHeader = () => {
    setFill(C.navyDark);
    doc.rect(M, y, CW, 1, 'F');
    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setText(C.cobalt);
    doc.text('EXECUTIVE PORTFOLIO ARCHITECTURE SPECIFICATION', M, y);
    doc.setFont('helvetica', 'normal');
    setText(C.textMuted);
    const rightLabel = `${data.userName || 'Client'} | ${data.archetype?.name || 'Authority Blueprint'}`;
    doc.text(rightLabel, PW - M, y, { align: 'right' });
    y += 5;
    setStroke(C.border);
    doc.setLineWidth(0.2);
    doc.line(M, y, PW - M, y);
    y += 6;
  };

  const drawFooter = () => {
    setStroke(C.border);
    doc.setLineWidth(0.3);
    doc.line(M, FOOTER_TOP - 2, PW - M, FOOTER_TOP - 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    setText(C.textMuted);
    doc.text('CONFIDENTIAL & PROPRIETARY — GENERATED BY AUTHORITY ARCHITECTURE SUITE', M, FOOTER_TOP + 2);
    doc.text(`Page ${pageNum}`, PW - M, FOOTER_TOP + 2, { align: 'right' });
  };

  const drawSectionBadge = (num: string, title: string) => {
    ensureSpace(14);
    setFill(C.indigoLight);
    setStroke(C.indigo);
    doc.setLineWidth(0.3);
    doc.roundedRect(M, y, CW, 8, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    setText(C.indigo);
    doc.text(`${num} — ${title.toUpperCase()}`, M + 4, y + 5.5);
    y += 12;
  };

  // ═══════════════════════════════════════════════════════════════════════════
  // COVER / EXECUTIVE HEADER BLOCK
  // ═══════════════════════════════════════════════════════════════════════════
  setFill(C.navyDark);
  doc.roundedRect(M, y, CW, 38, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  setText('#93c5fd');
  doc.text('MODULE 3 : STEP 3 : LEVEL 02 — ARCHITECTURE SPECIFICATION', M + 8, y + 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  setText('#ffffff');
  doc.text('Executive Portfolio Architecture & Wireframe Spec', M + 8, y + 17);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  setText('#cbd5e1');
  const subtitle = `High-Converting Authority Sales Funnel Spec prepared for ${data.userName || 'Specialist'}`;
  doc.text(subtitle, M + 8, y + 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  setText('#94a3b8');
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  doc.text(`DATE: ${dateStr}  |  ARCHETYPE: ${(data.archetype?.name || 'Proof-First Specialist').toUpperCase()}  |  SECTIONS: ${data.sections.filter(s => s.isEnabled !== false).length} ACTIVE`, M + 8, y + 32);

  y += 44;

  // ═══════════════════════════════════════════════════════════════════════════
  // SECTION 01: STRATEGIC FUNNEL & CONVERSION THESIS
  // ═══════════════════════════════════════════════════════════════════════════
  drawSectionBadge('SECTION 01', 'Strategic Funnel & Selected Archetype');

  // Archetype Card
  ensureSpace(28);
  setFill(C.cardBg);
  setStroke(C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(M, y, CW, 26, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  setText(C.navyDark);
  doc.text(`Archetype: ${data.archetype?.name || 'The Proof-First Specialist'}`, M + 4, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  setText(C.cobalt);
  doc.text(`FOCUS: ${data.archetype?.funnelFocus || 'Immediate proof demonstration above the fold'}`, M + 4, y + 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setText(C.textBody);
  const descLines = doc.splitTextToSize(data.archetype?.description || 'Engineered for high-skill specialists to convert cold prospects into booked discovery calls.', CW - 8);
  doc.text(descLines, M + 4, y + 18);

  y += 31;

  // Positioning & Mechanism Metadata Row
  ensureSpace(20);
  const halfW = (CW - 4) / 2;

  setFill('#f1f5f9');
  setStroke(C.border);
  doc.roundedRect(M, y, halfW, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  setText(C.textMuted);
  doc.text('PRIMARY POSITIONING HEADLINE', M + 3, y + 5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setText(C.textMain);
  const pLines = doc.splitTextToSize(data.positioningHeadline || 'Authority Specialist', halfW - 6);
  doc.text(pLines, M + 3, y + 10);

  setFill('#f1f5f9');
  doc.roundedRect(M + halfW + 4, y, halfW, 16, 2, 2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  setText(C.textMuted);
  doc.text('PROPRIETARY UNIQUE MECHANISM', M + halfW + 7, y + 5);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setText(C.cobalt);
  const mLines = doc.splitTextToSize(data.uniqueMechanism || 'Proof-First Delivery Framework', halfW - 6);
  doc.text(mLines, M + halfW + 7, y + 10);

  y += 22;

  // ═══════════════════════════════════════════════════════════════════════════
  // SECTION 02: 5-DIMENSION PORTFOLIO CONVERSION SCORECARD
  // ═══════════════════════════════════════════════════════════════════════════
  drawSectionBadge('SECTION 02', '5-Dimension Portfolio Conversion Audit');

  ensureSpace(42);
  // Main Score Box
  setFill(C.cobaltLight);
  setStroke(C.cobalt);
  doc.setLineWidth(0.4);
  doc.roundedRect(M, y, 42, 34, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  setText(C.cobalt);
  doc.text('CONVERSION SCORE', M + 4, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  setText(C.navyDark);
  doc.text(`${data.auditScore.totalScore}`, M + 4, y + 20);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  setText(C.emerald);
  doc.text(`/ 100 • ${data.auditScore.ratingLabel.toUpperCase()}`, M + 4, y + 28);

  // 5 Dimension Breakdown on Right
  const dimW = CW - 46;
  const dimX = M + 46;
  const dims = [
    data.auditScore.dimensionScores.hookClarity,
    data.auditScore.dimensionScores.proofProximity,
    data.auditScore.dimensionScores.offerClarity,
    data.auditScore.dimensionScores.objectionReadiness,
    data.auditScore.dimensionScores.ctaFriction,
  ];

  dims.forEach((d, i) => {
    const rowY = y + i * 7;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setText(C.textMain);
    doc.text(d.label, dimX, rowY + 4);

    const scoreStr = `${d.score}/${d.max} pts`;
    doc.setFont('helvetica', 'bold');
    setText(C.cobalt);
    doc.text(scoreStr, PW - M, rowY + 4, { align: 'right' });

    // Mini bar
    setStroke('#e2e8f0');
    doc.setLineWidth(1.2);
    doc.line(dimX, rowY + 6, PW - M - 20, rowY + 6);

    const fillRatio = Math.max(0.1, d.score / d.max);
    setStroke(C.cobalt);
    doc.setLineWidth(1.2);
    doc.line(dimX, rowY + 6, dimX + (PW - M - 20 - dimX) * fillRatio, rowY + 6);
  });

  y += 40;

  // ═══════════════════════════════════════════════════════════════════════════
  // SECTION 03: SECTION-BY-SECTION COPY & VISUAL LAYOUT SPECIFICATION
  // ═══════════════════════════════════════════════════════════════════════════
  addPage();
  drawSectionBadge('SECTION 03', 'Complete Website Architecture & Copy Vault');

  const activeSections = data.sections.filter((s) => s.isEnabled !== false);

  activeSections.forEach((sec, idx) => {
    ensureSpace(48);

    // Section Box Header
    setFill('#f8fafc');
    setStroke(C.border);
    doc.setLineWidth(0.3);
    doc.roundedRect(M, y, CW, 8, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    setText(C.navyDark);
    doc.text(`0${idx + 1}. ${sec.title.toUpperCase()}`, M + 3, y + 5.5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    setText(C.cobalt);
    doc.text(`CTA: ${sec.ctaText || 'None'}`, PW - M - 2, y + 5.5, { align: 'right' });
    y += 10;

    // Content Table
    const renderField = (label: string, value: string) => {
      if (!value) return;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      setText(C.textMuted);
      doc.text(label.toUpperCase(), M + 3, y);
      y += 3.5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      setText(C.textMain);
      const lines = doc.splitTextToSize(value, CW - 6);
      ensureSpace(lines.length * 4 + 4);
      doc.text(lines, M + 3, y);
      y += lines.length * 4 + 2;
    };

    if (sec.headline) renderField('Headline', sec.headline);
    if (sec.subheadline) renderField('Subheadline', sec.subheadline);
    if (sec.bodyCopy) renderField('Body Copy & Narrative', sec.bodyCopy);
    if (sec.conversionReasoning) renderField('Conversion Rationale', sec.conversionReasoning);
    if (sec.recommendedVisuals) renderField('Recommended Visual Components', sec.recommendedVisuals);
    if (sec.trustStatement) renderField('Trust Badge / Risk Reversal', sec.trustStatement);

    setStroke(C.border);
    doc.setLineWidth(0.2);
    doc.line(M, y, PW - M, y);
    y += 5;
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // SECTION 04: DESIGNER & DEVELOPER HANDOFF DIRECTIVES
  // ═══════════════════════════════════════════════════════════════════════════
  ensureSpace(40);
  drawSectionBadge('SECTION 04', 'Developer & Designer Implementation Guidelines');

  const guidelines = [
    { title: '1. Above-the-Fold Law', desc: 'Hero headline, subheadline, and primary CTA must be 100% visible on 1366x768 screens without scrolling.' },
    { title: '2. Verifiable Proof Priority', desc: 'Embed live interactive widgets, code snippets, or video demos in Section #2 or #3. Never bury proof.' },
    { title: '3. Single Unified Action', desc: 'Every CTA button across the page must route to the same conversion goal (e.g. Schedule Strategy Call).' },
    { title: '4. High-Contrast Typography', desc: 'Use dark navy (#0b1c30) on clean light canvas (#ffffff / #f8fafc) with electric blue (#0058be) accents.' },
  ];

  guidelines.forEach((g) => {
    ensureSpace(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    setText(C.navyDark);
    doc.text(g.title, M + 2, y);
    y += 3.5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    setText(C.textBody);
    doc.text(g.desc, M + 2, y);
    y += 5.5;
  });

  // Final page footer
  drawFooter();

  return doc;
}
