import { useMemo, useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { Check, Copy, FileText, Download, ArrowRight } from 'lucide-react';
import { useClientPipelineStore } from '../../lib/client-pipeline-system';
import { getServiceCategory, generatePipelineNextActions, isValidProspect } from '../../lib/blueprint-content';
import type { PipelineReport } from '../../types/client-pipeline-system';

function buildMarkdown(report: PipelineReport): string {
  const lines: string[] = [
    '# Client Pipeline Report',
    '',
    '---',
    '',
    '## 1. Client Source Map',
    '',
    ...report.clientSourceMap.sources.map((s) => `- **${s.sourceName}** (${s.difficulty}): ${s.whereToFind}`),
    '',
    '---',
    '',
    '## 2. Ideal Client Criteria',
    '',
    ...report.idealClientCriteria.criteria.map((c) => `- **${c.label}** (${c.priority}): ${c.whyItMatters}`),
    '',
    '---',
    '',
    '## 3. Prospect Types',
    '',
    ...report.prospectTypes.types.map((t) => `- **${t.name}** (${t.difficulty}, ${t.priority}): ${t.description}`),
    '',
    '---',
    '',
    '## 4. Search Queries',
    '',
    ...report.searchQueryBank.queries.map((q) => `- **${q.platform}**: \`${q.query}\``),
    '',
    '---',
    '',
    '## 5. Lead Scorecard',
    '',
    ...report.leadScorecard.factors.map((f) => `- **${f.name}**: ${f.score}/${f.maxScore}`),
    '',
    `**Total:** ${report.leadScorecard.total}/35 — ${report.leadScorecard.interpretation}`,
    '',
    '---',
    '',
    '## 6. Pipeline List',
    '',
    ...(() => {
      const valid = report.pipelineList.filter(isValidProspect);
      return [
        `**Valid Prospects:** ${valid.length}`,
        '',
        ...valid.map((e, i) =>
          `${i + 1}. **${e.prospectName}** (${e.platform}) — Score: ${e.score}/35, Priority: ${e.priority}, Status: ${e.status}`
        ),
      ];
    })(),
    '',
    '---',
    '',
    '## 7. Priority Plan',
    '',
    ...report.priorityPlan.entries.map((e, i) => {
      const why = e.whyWorthContacting?.length > 120 ? e.whyWorthContacting.slice(0, 120) + '...' : e.whyWorthContacting;
      return `${i + 1}. **${e.prospectName}** — ${why}`;
    }),
    '',
    ...(report.priorityPlan.entries.length > 0 ? [
      '',
      '### Priority Entry Details',
      ...report.priorityPlan.entries.map((e, i) => [
        '',
        `**${i + 1}. ${e.prospectName}**`,
        `- Why: ${e.whyWorthContacting}`,
        `- Angle: ${e.angleToUse}`,
        `- Asset: ${e.portfolioAssetToShow}`,
        `- Next Step: ${e.nextStep}`,
      ].join('\n')),
    ] : []),
    '',
    '---',
    '',
    '## 8. Next Actions',
    '',
    ...report.nextActions.map((a, i) => `${i + 1}. ${a}`),
    '',
    '---',
    '',
    '*Generated by Client Pipeline System — Module 5 of Client Acquisition System*',
    '',
  ];
  return lines.join('\n');
}

export function ClientPipelineReportStep() {
  const navigate = useNavigate();
  const clientSourceMap = useClientPipelineStore((s) => s.clientSourceMap);
  const idealClientCriteria = useClientPipelineStore((s) => s.idealClientCriteria);
  const prospectTypes = useClientPipelineStore((s) => s.prospectTypes);
  const searchQueryBank = useClientPipelineStore((s) => s.searchQueryBank);
  const leadScorecard = useClientPipelineStore((s) => s.leadScorecard);
  const pipelineList = useClientPipelineStore((s) => s.pipelineList);
  const priorityPlan = useClientPipelineStore((s) => s.priorityPlan);
  const report = useClientPipelineStore((s) => s.pipelineReport);
  const setReport = useClientPipelineStore((s) => s.setPipelineReport);
  const confirmStep = useClientPipelineStore((s) => s.confirmStep);
  const isCompleted = useClientPipelineStore((s) => s.completedSteps).includes('client_pipeline_report');
  const service = useClientPipelineStore((s) => s.phase4Service);
  const niche = useClientPipelineStore((s) => s.phase4Niche) ?? '';
  const [copied, setCopied] = useState(false);

  const cat = getServiceCategory(service);

  const downloadSlug = 'client-pipeline-report.md';

  const generatedReport = useMemo((): PipelineReport => {
    if (report) return report;
    const serviceId = service ?? undefined;
    return {
      clientSourceMap,
      idealClientCriteria,
      prospectTypes,
      searchQueryBank,
      leadScorecard,
      pipelineList,
      priorityPlan,
      nextActions: generatePipelineNextActions(cat, niche, serviceId),
    };
  }, [report, clientSourceMap, idealClientCriteria, prospectTypes, searchQueryBank, leadScorecard, pipelineList, priorityPlan, cat, niche, service]);

  const handleGenerate = () => {
    setReport(generatedReport);
    confirmStep();
  };

  const handleCopy = useCallback(async () => {
    const markdown = buildMarkdown(generatedReport);
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = markdown;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }, [generatedReport]);

  const handleDownload = useCallback(() => {
    const markdown = buildMarkdown(generatedReport);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = downloadSlug;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedReport]);

  if (!report) {
    return (
      <div className="space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-zinc-500">Step 8 of 8</span>
          <h2 className="text-2xl font-bold tracking-tight text-white/95">Generate Client Pipeline Report</h2>
          <p className="text-sm text-zinc-400 max-w-lg">
            Compile everything into a final client pipeline report.
          </p>
        </div>

        <div className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <FileText size={14} className="text-zinc-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="text-xs text-white/80 leading-relaxed">
              Review all pipeline sections and generate the final report. Once generated, you can copy or download as Markdown.
            </p>
          </div>
        </div>

        <ReportPreview report={generatedReport} />

        <motion.button
          onClick={handleGenerate}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-6 h-11 rounded-lg text-xs font-bold uppercase tracking-[0.08em] bg-white text-black hover:bg-white/90 shadow-[0_0_30px_-12px_rgba(255,255,255,0.15)] transition-all duration-300 cursor-pointer"
        >
          <Download size={14} />
          Generate Client Pipeline Report
        </motion.button>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-emerald-400">Step 8 of 8 — Complete</span>
        <h2 className="text-2xl font-bold tracking-tight text-white/95">Client Pipeline Report Generated</h2>
        <p className="text-sm text-zinc-400 max-w-lg">
          Your client pipeline is ready. Copy or download the report for reference.
        </p>
      </div>

      <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
        <Check size={14} className="text-emerald-400 shrink-0" />
        <span className="text-xs font-medium text-emerald-400">
          Client pipeline complete — all 8 steps finished
        </span>
      </div>

      <ReportPreview report={generatedReport} />

      <div className="flex items-center gap-3 pt-2 flex-wrap">
        <motion.button
          onClick={handleCopy}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <Copy size={12} />
          {copied ? 'Copied!' : 'Copy Report'}
        </motion.button>

        <motion.button
          onClick={handleDownload}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <FileText size={12} />
          Download Markdown
        </motion.button>

        <motion.button
          onClick={() => navigate('/workspace/outreach-engine')}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-brand-primary/10 border border-brand-primary/30 text-brand-primary hover:bg-brand-primary/15 transition-all duration-200 cursor-pointer"
        >
          <ArrowRight size={12} />
          Continue to Outreach Engine
        </motion.button>
      </div>
    </div>
  );
}

function ReportPreview({ report }: { report: PipelineReport }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <div className="p-5 border-b border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <FileText size={14} className="text-brand-primary" />
          <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-brand-primary">Client Pipeline Report</p>
        </div>
      </div>

      <div className="p-5 space-y-5 divide-y divide-white/[0.04]">
        <Section title="Client Source Map">
          <p className="text-[11px] text-zinc-400">{report.clientSourceMap.sources.length} source{report.clientSourceMap.sources.length !== 1 ? 's' : ''}</p>
          {report.clientSourceMap.sources.length > 0 ? (
            <div className="flex flex-wrap gap-1.5 mt-1">
              {report.clientSourceMap.sources.map((s, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {s.sourceName}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Ideal Client Criteria" className="pt-4">
          <p className="text-[11px] text-zinc-400">{report.idealClientCriteria.criteria.length} criteria</p>
          {report.idealClientCriteria.criteria.length > 0 ? (
            <div className="flex flex-wrap gap-1.5 mt-1">
              {report.idealClientCriteria.criteria.map((c, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {c.label}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Prospect Types" className="pt-4">
          {report.prospectTypes.types.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {report.prospectTypes.types.map((t, i) => (
                <span key={i} className="px-3 py-1.5 rounded-full bg-white/10 border border-white/10 text-[11px] font-medium text-white/80">
                  {t.name}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Search Queries" className="pt-4">
          <p className="text-[11px] text-zinc-400">{report.searchQueryBank.queries.length} quer{report.searchQueryBank.queries.length !== 1 ? 'ies' : 'y'}</p>
          {report.searchQueryBank.queries.length > 0 ? (
            <div className="flex flex-wrap gap-1.5 mt-1">
              {report.searchQueryBank.queries.map((q, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {q.platform}: {q.query.length > 30 ? q.query.slice(0, 30) + '...' : q.query}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Lead Scorecard" className="pt-4">
          {report.leadScorecard.factors.length > 0 ? (
            <div className="space-y-1">
              <div className="flex flex-wrap gap-1.5">
                {report.leadScorecard.factors.map((f, i) => (
                  <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                    {f.name}: {f.score}/{f.maxScore}
                  </span>
                ))}
              </div>
              <p className="text-[10px] text-white/70 mt-1">
                Total: {report.leadScorecard.total}/35 — {report.leadScorecard.interpretation}
              </p>
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Pipeline List" className="pt-4">
          {(() => {
            const valid = report.pipelineList.filter(isValidProspect);
            return (
              <>
                <p className="text-[11px] text-zinc-400">{valid.length} valid entr{valid.length !== 1 ? 'ies' : 'y'}</p>
                {valid.length > 0 ? (
                  <div className="space-y-1 mt-1">
                    {valid.slice(0, 5).map((e, i) => (
                      <p key={e.id} className="text-[10px] text-zinc-400">
                        {e.prospectName} ({e.platform}) — {e.score}/35
                      </p>
                    ))}
                    {valid.length > 5 && (
                      <p className="text-[9px] text-zinc-500">+{valid.length - 5} more</p>
                    )}
                  </div>
                ) : <Empty />}
              </>
            );
          })()}
        </Section>

        <Section title="Priority Plan" className="pt-4">
          {report.priorityPlan.entries.length > 0 ? (
            <div className="space-y-2">
              {report.priorityPlan.entries.map((e, i) => (
                <div key={i} className="flex items-start gap-2 text-[10px] text-zinc-400">
                  <span className="flex items-center justify-center w-4 h-4 rounded-full bg-brand-primary/15 text-[7px] font-bold text-brand-primary shrink-0 mt-0.5">
                    {i + 1}
                  </span>
                  <span>{e.prospectName}: {e.whyWorthContacting}</span>
                </div>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Next Actions" className="pt-4">
          <ul className="space-y-1.5">
            {report.nextActions.map((action, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                <span className="flex items-center justify-center w-4 h-4 rounded-full bg-brand-primary/15 text-[8px] font-bold text-brand-primary shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {action}
              </li>
            ))}
          </ul>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children, className }: { title: string; children: React.ReactNode; className?: string }) {
  return (
    <div className={className || ''}>
      <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500 mb-2">{title}</p>
      {children}
    </div>
  );
}

function Empty() {
  return <p className="text-sm text-zinc-500">—</p>;
}
