import { useMemo, useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { Check, Copy, FileText, Download, ArrowRight, ShieldCheck, Shield, ShieldAlert, UserCheck, Radio, Compass, Target, BarChart3 } from 'lucide-react';
import { useClientPipelineStore } from '../../lib/client-pipeline-system';
import { cn } from '../../lib/utils';

function buildMarkdown(report: {
  profileTitle: string;
  profileDescription: string;
  characteristics: string[];
  evidenceOfFit: string[];
  buyingSignals: { signal: string; whyItMatters: string }[];
  disqualifiers: string[];
  channels: { platform: string; priority: string; channelType: string }[];
  qualificationFactors: { name: string; weight: number; whyImportant: string }[];
  pipelineCount: number;
  priorityProspects: string[];
  readinessStatus: string;
  readinessReasons: string[];
  portfolioAssetAvailable: boolean;
  portfolioAssetTitle?: string;
  portfolioAssetUrl?: string;
  m6Handoff: { portfolioHeadline?: string; portfolioUrl?: string; positioning?: string; deliverables: string[] };
}): string {
  const lines: string[] = [
    '# Client Pipeline Report',
    '',
    '---',
    '',
    '## 1. Ideal Prospect Profile',
    '',
    `**${report.profileTitle}**`,
    '',
    report.profileDescription,
    '',
    '### Characteristics',
    ...report.characteristics.map((c) => `- ${c}`),
    '',
    '### Evidence of Fit',
    ...report.evidenceOfFit.map((e) => `- ${e}`),
    '',
    '---',
    '',
    '## 2. Buying Signals',
    '',
    ...report.buyingSignals.map((s) => `- **${s.signal}** — ${s.whyItMatters}`),
    '',
    ...(report.disqualifiers.length > 0 ? [
      '### Do Not Pursue',
      ...report.disqualifiers.map((d) => `- ${d}`),
      '',
    ] : []),
    '---',
    '',
    '## 3. Priority Discovery Channels',
    '',
    ...report.channels.map((c) => `- **${c.platform}** (${c.priority}): ${c.channelType}`),
    '',
    '---',
    '',
    '## 4. Qualification Approach',
    '',
    ...report.qualificationFactors.map((f) => `- **${f.name}** (max: ${f.weight}): ${f.whyImportant}`),
    '',
    '---',
    '',
    '## 5. Pipeline Summary',
    '',
    `**Qualified Prospects:** ${report.pipelineCount}`,
    '',
    '---',
    '',
    '## 6. Priority Prospects',
    '',
    ...report.priorityProspects.map((name, i) => `${i + 1}. ${name}`),
    '',
    '---',
    '',
    '## 7. Prospecting Readiness',
    '',
    `**Status:** ${report.readinessStatus}`,
    ...report.readinessReasons.map((r) => `- ${r}`),
    '',
    '---',
    '',
    '## 8. Portfolio Lead Asset',
    '',
    report.portfolioAssetAvailable
      ? `- **Available:** ${report.portfolioAssetTitle || 'Yes'}\n- **URL:** ${report.portfolioAssetUrl || 'N/A'}`
      : '- No portfolio lead asset available — prospecting is limited',
    '',
    '---',
    '',
    '## 9. Module 6 Handoff Context',
    '',
    ...(report.m6Handoff.positioning ? [`- **Positioning:** ${report.m6Handoff.positioning}`] : []),
    ...(report.m6Handoff.portfolioHeadline ? [`- **Portfolio:** ${report.m6Handoff.portfolioHeadline}`] : []),
    ...(report.m6Handoff.portfolioUrl ? [`- **Portfolio URL:** ${report.m6Handoff.portfolioUrl}`] : []),
    ...(report.m6Handoff.deliverables.length > 0 ? [`- **Deliverables:** ${report.m6Handoff.deliverables.join(', ')}`] : []),
    '',
    '---',
    '',
    '*Generated by Client Pipeline System — Module 5 of Client Acquisition System*',
    '',
  ];
  return lines.join('\n');
}

export function ClientPipelineReportStep() {
  const navigate = useNavigate();
  const pipelinePack = useClientPipelineStore((s) => s.pipelinePack);
  const pipelineList = useClientPipelineStore((s) => s.pipelineList);
  const leadScorecard = useClientPipelineStore((s) => s.leadScorecard);
  const report = useClientPipelineStore((s) => s.pipelineReport);
  const setReport = useClientPipelineStore((s) => s.setPipelineReport);
  const confirmStep = useClientPipelineStore((s) => s.confirmStep);
  const isCompleted = useClientPipelineStore((s) => s.completedSteps).includes('client_pipeline_report');
  const [copied, setCopied] = useState(false);

  const downloadSlug = 'client-pipeline-report.md';

  // Build report data from pipelinePack + pipelineList
  const reportData = useMemo(() => {
    if (!pipelinePack) return null;

    const validEntries = pipelineList.filter(
      (p) => p.prospectName?.trim() || p.websiteUrl?.trim()
    );
    const scoredEntries = validEntries.filter((p) => p.score > 0)
      .sort((a, b) => b.score - a.score);

    return {
      profileTitle: pipelinePack.idealProspectProfile.title,
      profileDescription: pipelinePack.idealProspectProfile.description,
      characteristics: pipelinePack.idealProspectProfile.characteristics,
      evidenceOfFit: pipelinePack.idealProspectProfile.evidenceOfFit,
      buyingSignals: pipelinePack.buyingSignals,
      disqualifiers: pipelinePack.disqualifiers,
      channels: pipelinePack.targetChannels.map((c) => ({
        platform: c.platform,
        priority: c.priority,
        channelType: c.channelType,
      })),
      qualificationFactors: pipelinePack.qualificationFactors,
      pipelineCount: validEntries.length,
      priorityProspects: scoredEntries.slice(0, 10).map((e) => e.prospectName || 'Unnamed'),
      readinessStatus: pipelinePack.prospectingReadiness.status,
      readinessReasons: pipelinePack.prospectingReadiness.reasons,
      portfolioAssetAvailable: pipelinePack.portfolioLeadAsset.available,
      portfolioAssetTitle: pipelinePack.portfolioLeadAsset.title,
      portfolioAssetUrl: pipelinePack.portfolioLeadAsset.url,
      m6Handoff: {
        portfolioHeadline: pipelinePack.module6HandoffContext.portfolioHeadline,
        portfolioUrl: pipelinePack.module6HandoffContext.portfolioUrl,
        portfolioCta: pipelinePack.module6HandoffContext.portfolioCta,
        positioning: pipelinePack.module6HandoffContext.positioning,
        deliverables: pipelinePack.module6HandoffContext.deliverables,
        featuredProofTitle: pipelinePack.module6HandoffContext.featuredProofTitle,
        featuredProofUrl: pipelinePack.module6HandoffContext.featuredProofUrl,
      },
    };
  }, [pipelinePack, pipelineList]);

  const handleGenerate = () => {
    if (!reportData) return;
    setReport({
      clientSourceMap: { sources: [] },
      idealClientCriteria: { criteria: [] },
      prospectTypes: { types: [] },
      searchQueryBank: { queries: [] },
      leadScorecard,
      pipelineList,
      priorityPlan: { entries: [] },
      nextActions: [
        `Review priority prospects (${reportData.priorityProspects.length} identified)`,
        `Prepare outreach for ${reportData.readinessStatus === 'ready' ? 'top-priority' : 'available'} prospects`,
        reportData.portfolioAssetAvailable
          ? `Lead with "${reportData.portfolioAssetTitle || 'featured proof'}" in conversations`
          : 'Build portfolio proof asset before active outreach',
        'Proceed to Outreach Engine (Module 6) for messaging and sequences',
      ],
    });
    confirmStep();
  };

  const handleCopy = useCallback(async () => {
    if (!reportData) return;
    const markdown = buildMarkdown(reportData);
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = markdown;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }, [reportData]);

  const handleDownload = useCallback(() => {
    if (!reportData) return;
    const markdown = buildMarkdown(reportData);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = downloadSlug;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [reportData]);

  if (!pipelinePack || !reportData) {
    return (
      <div className="space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-zinc-500">Step 8 of 8</span>
          <h2 className="text-2xl font-bold tracking-tight text-white/95">Generate Client Pipeline Report</h2>
          <p className="text-sm text-zinc-400 max-w-lg">
            Compile everything into a final client pipeline report.
          </p>
        </div>
        <div className="flex items-center justify-center p-8 rounded-xl bg-white/[0.02] border border-white/5">
          <div className="text-center space-y-2">
            <p className="text-sm text-zinc-500">Pipeline strategy not yet generated.</p>
            <p className="text-[11px] text-zinc-600">Complete upstream modules and return here.</p>
          </div>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-zinc-500">Step 8 of 8</span>
          <h2 className="text-2xl font-bold tracking-tight text-white/95">Client Pipeline Report</h2>
          <p className="text-sm text-zinc-400 max-w-lg">
            Review your full pipeline strategy and generate the final report.
          </p>
        </div>

        <div className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <FileText size={14} className="text-zinc-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="text-xs text-white/80 leading-relaxed">
              The report summarises your prospect profile, signals, channels, qualification approach, pipeline, priority prospects, readiness, and Module 6 handoff context.
            </p>
          </div>
        </div>

        <ReportPreview data={reportData} />

        <motion.button
          onClick={handleGenerate}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-6 h-11 rounded-lg text-xs font-bold uppercase tracking-[0.08em] bg-white text-black hover:bg-white/90 shadow-[0_0_30px_-12px_rgba(255,255,255,0.15)] transition-all duration-300 cursor-pointer"
        >
          <Download size={14} />
          Generate Client Pipeline Report
        </motion.button>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-emerald-400">Step 8 of 8 — Complete</span>
        <h2 className="text-2xl font-bold tracking-tight text-white/95">Client Pipeline Report Generated</h2>
        <p className="text-sm text-zinc-400 max-w-lg">
          Your client pipeline is ready. Copy or download the report for reference.
        </p>
      </div>

      <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
        <Check size={14} className="text-emerald-400 shrink-0" />
        <span className="text-xs font-medium text-emerald-400">
          Client pipeline complete — all 8 steps finished
        </span>
      </div>

      <ReportPreview data={reportData} />

      <div className="flex items-center gap-3 pt-2 flex-wrap">
        <motion.button
          onClick={handleCopy}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <Copy size={12} />
          {copied ? 'Copied!' : 'Copy Report'}
        </motion.button>

        <motion.button
          onClick={handleDownload}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <FileText size={12} />
          Download Markdown
        </motion.button>

        <motion.button
          onClick={() => navigate('/workspace/outreach-engine')}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-brand-primary/10 border border-brand-primary/30 text-brand-primary hover:bg-brand-primary/15 transition-all duration-200 cursor-pointer"
        >
          <ArrowRight size={12} />
          Continue to Outreach Engine
        </motion.button>
      </div>
    </div>
  );
}

function ReportPreview({ data }: {
  data: {
    profileTitle: string;
    profileDescription: string;
    characteristics: string[];
    evidenceOfFit: string[];
    buyingSignals: { signal: string; whyItMatters: string }[];
    disqualifiers: string[];
    channels: { platform: string; priority: string; channelType: string }[];
    qualificationFactors: { name: string; weight: number; whyImportant: string }[];
    pipelineCount: number;
    priorityProspects: string[];
    readinessStatus: string;
    readinessReasons: string[];
    portfolioAssetAvailable: boolean;
    portfolioAssetTitle?: string;
    portfolioAssetUrl?: string;
    m6Handoff: {
      portfolioHeadline?: string;
      portfolioUrl?: string;
      positioning?: string;
      deliverables: string[];
      featuredProofTitle?: string;
      featuredProofUrl?: string;
    };
  };
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <div className="p-5 border-b border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <FileText size={14} className="text-brand-primary" />
          <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-brand-primary">Client Pipeline Report</p>
        </div>
      </div>

      <div className="p-5 space-y-5 divide-y divide-white/[0.04]">
        {/* 1. Profile */}
        <div className="pt-0">
          <div className="flex items-center gap-2 mb-2">
            <UserCheck size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Ideal Prospect Profile</p>
          </div>
          <p className="text-sm font-semibold text-white/90 mb-1">{data.profileTitle}</p>
          <p className="text-[11px] text-zinc-400 mb-2">{data.profileDescription}</p>
          {data.characteristics.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {data.characteristics.slice(0, 4).map((c, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {c.length > 40 ? c.slice(0, 40) + '...' : c}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* 2. Buying Signals */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            <Radio size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Buying Signals ({data.buyingSignals.length})</p>
          </div>
          {data.buyingSignals.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {data.buyingSignals.map((s, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {s.signal.length > 50 ? s.signal.slice(0, 50) + '...' : s.signal}
                </span>
              ))}
            </div>
          ) : <p className="text-[11px] text-zinc-500">—</p>}
        </div>

        {/* 3. Channels */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            <Compass size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Discovery Channels ({data.channels.length})</p>
          </div>
          {data.channels.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {data.channels.map((c, i) => (
                <span key={i} className={cn(
                  'px-2 py-0.5 rounded text-[9px] border',
                  c.priority === 'high'
                    ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400'
                    : c.priority === 'medium'
                      ? 'bg-amber-500/10 border-amber-500/20 text-amber-400'
                      : 'bg-zinc-500/10 border-zinc-500/20 text-zinc-400',
                )}>
                  {c.platform}
                </span>
              ))}
            </div>
          ) : <p className="text-[11px] text-zinc-500">—</p>}
        </div>

        {/* 4. Qualification */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            <BarChart3 size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Qualification Factors ({data.qualificationFactors.length})</p>
          </div>
          {data.qualificationFactors.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {data.qualificationFactors.map((f, i) => (
                <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                  {f.name} (max {f.weight})
                </span>
              ))}
            </div>
          ) : <p className="text-[11px] text-zinc-500">—</p>}
        </div>

        {/* 5. Pipeline */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            <Target size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Pipeline Summary</p>
          </div>
          <p className="text-[11px] text-zinc-400">{data.pipelineCount} total prospects</p>
          {data.priorityProspects.length > 0 && (
            <div className="space-y-1 mt-2">
              <p className="text-[8px] font-bold uppercase tracking-[0.12em] text-zinc-500">Priority Prospects</p>
              {data.priorityProspects.slice(0, 5).map((name, i) => (
                <p key={i} className="text-[10px] text-zinc-400">{i + 1}. {name}</p>
              ))}
            </div>
          )}
        </div>

        {/* 6. Readiness */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            {data.readinessStatus === 'ready'
              ? <ShieldCheck size={12} className="text-emerald-400" />
              : data.readinessStatus === 'limited'
                ? <Shield size={12} className="text-amber-400" />
                : <ShieldAlert size={12} className="text-red-400" />}
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Prospecting Readiness: {data.readinessStatus}</p>
          </div>
          {data.readinessReasons.length > 0 && (
            <ul className="space-y-0.5">
              {data.readinessReasons.map((r, i) => (
                <li key={i} className="text-[10px] text-zinc-500">{r}</li>
              ))}
            </ul>
          )}
        </div>

        {/* 7. Portfolio Lead Asset */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            {data.portfolioAssetAvailable
              ? <ShieldCheck size={12} className="text-emerald-400" />
              : <Shield size={12} className="text-zinc-400" />}
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">
              {data.portfolioAssetAvailable ? 'Portfolio Lead Asset Available' : 'No Portfolio Lead Asset'}
            </p>
          </div>
          {data.portfolioAssetAvailable && data.portfolioAssetTitle && (
            <p className="text-[10px] text-zinc-300">{data.portfolioAssetTitle}</p>
          )}
          {data.portfolioAssetUrl && (
            <p className="text-[9px] text-zinc-500 font-mono">{data.portfolioAssetUrl}</p>
          )}
        </div>

        {/* 8. M6 Handoff */}
        <div className="pt-4">
          <div className="flex items-center gap-2 mb-2">
            <ArrowRight size={12} className="text-brand-primary" />
            <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500">Module 6 Handoff</p>
          </div>
          <div className="space-y-1">
            {data.m6Handoff.positioning && <p className="text-[10px] text-zinc-400">Positioning: {data.m6Handoff.positioning}</p>}
            {data.m6Handoff.portfolioHeadline && <p className="text-[10px] text-zinc-400">Portfolio: {data.m6Handoff.portfolioHeadline}</p>}
            {data.m6Handoff.deliverables.length > 0 && (
              <p className="text-[10px] text-zinc-400">Deliverables: {data.m6Handoff.deliverables.join(', ')}</p>
            )}
            {data.m6Handoff.featuredProofTitle && (
              <p className="text-[10px] text-zinc-400">Proof: {data.m6Handoff.featuredProofTitle}</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
