import { useMemo, useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { Check, Copy, FileText, Shield, Download, ArrowRight } from 'lucide-react';
import { useAuthoritySystemStore } from '../../lib/authority-system';
import type { AuthorityReport, TrustBuilderItem } from '../../types/authority-system';

function buildMarkdown(report: AuthorityReport): string {
  const lines: string[] = [
    '# Authority System Report',
    '',
    '---',
    '',
    '## Authority Position',
    '',
    `**Angle:** ${report.authorityAngle || '—'}`,
    `**Credibility Level:** ${report.credibilityLevel || '—'}`,
    `**Trust Promise:** ${report.trustPromise || '—'}`,
    `**Position Statement:** ${report.authorityPosition}`,
    '',
    '---',
    '',
    '## Proof Assets',
    ...report.proofAssets.map((a) => [
      '',
      `### ${a.title || a.type.replace(/_/g, ' ')}`,
      `- Type: ${a.type.replace(/_/g, ' ')}`,
      `- What to create: ${a.whatToCreate}`,
      `- Why it builds trust: ${a.whyItBuildsTrust}`,
      `- Est. time: ${a.estimatedTime}`,
      `- Difficulty: ${a.difficulty}`,
    ].join('\n')),
    '',
    '---',
    '',
    '## Portfolio Asset Plan',
    ...report.portfolioAssets.map((a) => [
      '',
      `### ${a.name}`,
      `- Format: ${a.format}`,
      `- Description: ${a.description}`,
      `- What to Include: ${a.whatToInclude}`,
      `- Where to Publish: ${a.whereToPublish}`,
      `- CTA: ${a.cta}`,
    ].join('\n')),
    '',
    '---',
    '',
    '## Trust Builder Checklist',
    ...report.trustBuilderChecklist.map((item: TrustBuilderItem) =>
      `- [${item.status === 'ready' ? 'x' : ' '}] **${item.label}** (${item.status}) — ${item.action}`
    ),
    '',
    '---',
    '',
    '## Social Proof Plan',
    '',
    `**Current Proof:** ${report.socialProofPlan.currentProof || '—'}`,
    `**Missing Proof:** ${report.socialProofPlan.missingProof || '—'}`,
    '',
    '**Next Actions:**',
    ...report.socialProofPlan.nextActions.map((a, i) => `  ${i + 1}. ${a}`),
    '',
    '---',
    '',
    '## Content Asset Plan',
    ...report.contentAssets.map((a) => [
      '',
      `### ${a.title}`,
      `- Hook: ${a.hook}`,
      `- Format: ${a.format}`,
      `- Main Points: ${a.mainPoints}`,
      `- CTA: ${a.cta}`,
      `- Platform: ${a.platformSuggestion}`,
    ].join('\n')),
    '',
    '---',
    '',
    '## Authority Profile',
    '',
    `**One-Line:** ${report.authorityProfile.oneLinePositioning}`,
    `**Short Bio:** ${report.authorityProfile.shortBio}`,
    ...(report.authorityProfile.serviceDescription ? [`**Service Description:** ${report.authorityProfile.serviceDescription}`] : []),
    '',
    '**Trust Bullets:**',
    ...report.authorityProfile.trustBullets.map((b) => `- ${b}`),
    '',
    `**CTA:** ${report.authorityProfile.ctaLine}`,
    '',
    '---',
    '',
    '## Next Actions',
    ...report.nextActions.map((a, i) => `${i + 1}. ${a}`),
    '',
    '---',
    '',
    '*Generated by Authority System — Phase 3 of Client Acquisition System*',
    '',
  ];
  return lines.join('\n');
}

const DEFAULT_NEXT_ACTIONS = [
  'Create your selected proof assets',
  'Build your 3 portfolio assets with the defined format and CTA',
  'Implement trust builder checklist items — start with pending items first',
  'Execute your next 3 social proof building actions',
  'Publish your 5 content assets on recommended platforms',
  'Update your LinkedIn/profile with authority profile copy',
  'Use authority position statement in outreach messages',
];

export function AuthorityReportStep() {
  const authorityAngle = useAuthoritySystemStore((s) => s.authorityAngle) ?? '';
  const credibilityLevel = useAuthoritySystemStore((s) => s.credibilityLevel) ?? '';
  const trustPromise = useAuthoritySystemStore((s) => s.trustPromise) ?? '';
  const authorityPosition = useAuthoritySystemStore((s) => s.authorityPosition) ?? '';
  const proofAssets = useAuthoritySystemStore((s) => s.proofAssets) ?? [];
  const portfolioAssets = useAuthoritySystemStore((s) => s.portfolioAssets) ?? [];
  const trustBuilderChecklist = useAuthoritySystemStore((s) => s.trustBuilderChecklist) ?? [];
  const rawSocialProofPlan = useAuthoritySystemStore((s) => s.socialProofPlan);
  const socialProofPlan = rawSocialProofPlan ?? { currentProof: '', missingProof: '', nextActions: [] };
  const contentAssets = useAuthoritySystemStore((s) => s.contentAssets) ?? [];
  const rawAuthorityProfile = useAuthoritySystemStore((s) => s.authorityProfile);
  const authorityProfile = rawAuthorityProfile ?? { oneLinePositioning: '', shortBio: '', serviceDescription: '', trustBullets: [], ctaLine: '' };
  const report = useAuthoritySystemStore((s) => s.authorityReport);
  const setReport = useAuthoritySystemStore((s) => s.setAuthorityReport);
  const confirmStep = useAuthoritySystemStore((s) => s.confirmStep);
  const isCompleted = useAuthoritySystemStore((s) => s.completedSteps).includes('authority_report');
  const offerName = useAuthoritySystemStore((s) => s.phase2OfferName) ?? '';
  const downloadSlug = offerName
    ? offerName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '-authority-report.md'
    : 'authority-system-report.md';
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();

  const generatedReport = useMemo((): AuthorityReport => {
    if (report) return report;
    return {
      authorityPosition,
      authorityAngle,
      credibilityLevel,
      trustPromise,
      proofAssets,
      portfolioAssets,
      trustBuilderChecklist,
      socialProofPlan,
      contentAssets,
      authorityProfile,
      nextActions: DEFAULT_NEXT_ACTIONS,
    };
  }, [report, authorityAngle, credibilityLevel, trustPromise, authorityPosition, proofAssets, portfolioAssets, trustBuilderChecklist, socialProofPlan, contentAssets, authorityProfile]);

  const handleGenerate = () => {
    setReport(generatedReport);
    confirmStep();
  };

  const handleCopy = useCallback(async () => {
    const markdown = buildMarkdown(generatedReport);
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = markdown;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }, [generatedReport]);

  const handleDownload = useCallback(() => {
    const markdown = buildMarkdown(generatedReport);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
      a.download = downloadSlug;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedReport]);

  if (!report) {
    return (
      <div className="space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-zinc-500">Step 8 of 8</span>
          <h2 className="text-2xl font-bold tracking-tight text-white/95">Generate Authority Report</h2>
          <p className="text-sm text-zinc-400 max-w-lg">
            Compile everything into a final authority system report you can use as a reference.
          </p>
        </div>

        <div className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <Shield size={14} className="text-zinc-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="text-xs text-white/80 leading-relaxed">
              Review all sections and generate the final report. Once generated, you can copy or download as Markdown.
            </p>
          </div>
        </div>

        <ReportPreview report={generatedReport} />

        <motion.button
          onClick={handleGenerate}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-6 h-11 rounded-lg text-xs font-bold uppercase tracking-[0.08em] bg-white text-black hover:bg-white/90 shadow-[0_0_30px_-12px_rgba(255,255,255,0.15)] transition-all duration-300 cursor-pointer"
        >
          <Download size={14} />
          Generate Authority Report
        </motion.button>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-emerald-400">Step 8 of 8 — Complete</span>
        <h2 className="text-2xl font-bold tracking-tight text-white/95">Authority Report Generated</h2>
        <p className="text-sm text-zinc-400 max-w-lg">
          Your authority system is ready. Copy or download the report for reference.
        </p>
      </div>

      <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
        <Check size={14} className="text-emerald-400 shrink-0" />
        <span className="text-xs font-medium text-emerald-400">
          Authority system complete — all 8 steps finished
        </span>
      </div>

      <ReportPreview report={generatedReport} />

      <div className="flex items-center gap-3 pt-2 flex-wrap">
        <motion.button
          onClick={handleCopy}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <Copy size={12} />
          {copied ? 'Copied!' : 'Copy Text'}
        </motion.button>

        <motion.button
          onClick={handleDownload}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <FileText size={12} />
          Download Markdown
        </motion.button>

        <motion.button
          onClick={() => navigate('/workspace/portfolio-system')}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white text-black hover:bg-white/90 shadow-[0_0_30px_-12px_rgba(255,255,255,0.15)] transition-all duration-200 cursor-pointer"
        >
          <ArrowRight size={12} />
          Continue to Portfolio System
        </motion.button>
      </div>
    </div>
  );
}

function ReportPreview({ report }: { report: AuthorityReport }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <div className="p-5 border-b border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <Shield size={14} className="text-brand-primary" />
          <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-brand-primary">Authority Report</p>
        </div>
        <p className="text-sm text-white/80 leading-relaxed">{report.authorityPosition}</p>
        <div className="flex flex-wrap gap-2 mt-2">
          <span className="text-[8px] px-1.5 py-0.5 rounded bg-white/5 text-zinc-400">{report.authorityAngle}</span>
          <span className="text-[8px] px-1.5 py-0.5 rounded bg-white/5 text-zinc-400">{report.credibilityLevel}</span>
        </div>
      </div>

      <div className="p-5 space-y-5 divide-y divide-white/[0.04]">
        <Section title="Proof Assets">
          {report.proofAssets.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {report.proofAssets.map((a, i) => (
                <span key={i} className="px-3 py-1.5 rounded-full bg-white/10 border border-white/10 text-[11px] font-medium text-white/80">
                  {a.title || a.type.replace(/_/g, ' ')}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Trust Builder" className="pt-4">
          {report.trustBuilderChecklist.length > 0 ? (
            <div className="space-y-1">
              {report.trustBuilderChecklist.map((item, i) => (
                <div key={i} className="flex items-center gap-2 text-xs text-white/70">
                  <span className={`w-3 h-3 rounded flex items-center justify-center text-[6px] font-bold ${
                    item.status === 'ready' ? 'bg-emerald-500/20 text-emerald-400' :
                    item.status === 'in_progress' ? 'bg-amber-400/10 text-amber-400' :
                    'bg-zinc-500/20 text-zinc-500'
                  }`}>
                    {item.status === 'ready' ? '✓' : item.status === 'in_progress' ? '…' : '○'}
                  </span>
                  {item.label}
                </div>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Social Proof Strategy" className="pt-4">
          <div className="text-xs text-zinc-400 space-y-1">
            <p><span className="text-zinc-500">Current:</span> {report.socialProofPlan.currentProof || '—'}</p>
            <p><span className="text-zinc-500">Missing:</span> {report.socialProofPlan.missingProof || '—'}</p>
          </div>
          {report.socialProofPlan.nextActions.length > 0 && (
            <div className="mt-2 space-y-0.5">
              {report.socialProofPlan.nextActions.filter(Boolean).map((a, i) => (
                <p key={i} className="text-[10px] text-white/60 flex items-start gap-1.5">
                  <span className="text-brand-primary">{i + 1}.</span> {a}
                </p>
              ))}
            </div>
          )}
        </Section>

        <Section title="Content Assets" className="pt-4">
          {report.contentAssets.length > 0 ? (
            <div className="space-y-2">
              {report.contentAssets.map((a, i) => (
                <div key={i} className="p-3 rounded-lg bg-white/[0.02] border border-white/5">
                  <p className="text-xs font-semibold text-white/80">{a.title}</p>
                  <p className="text-[9px] text-zinc-500 mt-0.5">{a.format} · {a.platformSuggestion}</p>
                </div>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Authority Profile" className="pt-4">
          {report.authorityProfile.oneLinePositioning ? (
            <div className="space-y-2">
              <p className="text-sm text-white/80 font-medium">{report.authorityProfile.oneLinePositioning}</p>
              <p className="text-xs text-zinc-400">{report.authorityProfile.shortBio}</p>
              {report.authorityProfile.trustBullets.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {report.authorityProfile.trustBullets.filter(Boolean).map((b, i) => (
                    <span key={i} className="px-2 py-1 rounded bg-brand-primary/10 text-[9px] font-medium text-brand-primary">{b}</span>
                  ))}
                </div>
              )}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Next Actions" className="pt-4">
          <ul className="space-y-1.5">
            {report.nextActions.map((action, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                <span className="flex items-center justify-center w-4 h-4 rounded-full bg-brand-primary/15 text-[8px] font-bold text-brand-primary shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {action}
              </li>
            ))}
          </ul>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children, className }: { title: string; children: React.ReactNode; className?: string }) {
  return (
    <div className={className || ''}>
      <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500 mb-2">{title}</p>
      {children}
    </div>
  );
}

function Empty() {
  return <p className="text-sm text-zinc-500">—</p>;
}
