import { useMemo, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import {
  FileText, Check, Download, ArrowLeft, Users, AlertCircle, Target,
  Package, Lightbulb, Clock, Shield, Zap, DollarSign, TrendingUp, ArrowRight, Copy,
  Edit3, Save, FileDown
} from 'lucide-react';
import { useOfferEngineeringStore, getEngineeringDataForService, useModule2ResolvedContent } from '../../lib/offer-engineering';
import { useOpportunityMapStore } from '../../lib/opportunity-map';
import { exportBlueprintPDF, polishedOfferTitle } from '../../lib/offer-engineering/pdf-export';
import { cn } from '../../lib/utils';
import type { OfferBlueprint } from '../../types/offer-engineering';
import { getServiceCategory, getAudienceLabel, generateWhoItIsFor, generateProblemItSolves, generateCorePromise, generateWhyThisWorks, generateNextStepCTA, generateNicheValueAmplifier } from '../../lib/blueprint-content';

function buildMarkdown(bp: OfferBlueprint): string {
  const lines: string[] = [
    `# ${bp.offerName}`,
    '',
    `**Productized Service:** ${bp.productizedService}`,
    '',
    '---',
    '',
    '## 1. Who It Is For',
    bp.whoItIsFor,
    '',
    '## 2. Problem It Solves',
    bp.problemItSolves,
    '',
    '## 3. Core Promise',
    bp.corePromise,
    '',
    '## 4. Deliverables',
    ...(bp.deliverables.length > 0 ? bp.deliverables.map((d) => `- ${d}`) : ['—']),
    '',
    '## 5. Unique Mechanism',
    bp.uniqueMechanism,
    '',
    '## 6. Timeline',
    bp.timeline,
    '',
    '## 7. Scope Rules',
    `- Revisions: ${bp.scopeLimits.revisionCount}`,
    `- Feedback Rounds: ${bp.scopeLimits.includedRounds}`,
    `- Delivery: ${bp.scopeLimits.deliveryTime}`,
    `- Response Time: ${bp.scopeLimits.responseTime}`,
    `- Communication: ${bp.scopeLimits.communicationMethod}`,
    '',
    '## 8. Value Amplifier',
    bp.valueAmplifier,
    '',
    '## 9. Pricing',
    bp.pricingStructure,
    ...(bp.pricingModel === 'tiered'
      ? [
          '',
          `- Starter: ${bp.tieredPricing.starterPrice !== null && bp.tieredPricing.starterPrice > 0 ? `$${bp.tieredPricing.starterPrice}` : 'TBD'}`,
          `- Pro: ${bp.tieredPricing.proPrice !== null && bp.tieredPricing.proPrice > 0 ? `$${bp.tieredPricing.proPrice}` : 'TBD'}`,
          `- Premium: ${bp.tieredPricing.premiumPrice !== null && bp.tieredPricing.premiumPrice > 0 ? `$${bp.tieredPricing.premiumPrice}` : 'TBD'}`,
        ]
      : []),
    ...(bp.pricingModel === 'value_based'
      ? [
          '',
          `- Estimated Client Value: ${bp.valueBasedPricing.estimatedClientValue !== null && bp.valueBasedPricing.estimatedClientValue > 0 ? `$${bp.valueBasedPricing.estimatedClientValue}` : 'TBD'}`,
          ...(bp.valueBasedPricing.impactLevel ? [`- Impact: ${bp.valueBasedPricing.impactLevel}`] : []),
        ]
      : []),
    '',
    '## 10. Why This Works',
    bp.whyThisWorks,
    '',
    '## 11. Next Step',
    bp.nextStepCTA,
    '',
    '---',
    '',
    `*Generated by Offer Engineering — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`,
    '',
  ];
  return lines.join('\n');
}

function getSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'offer-blueprint';
}

function p(v: number | null): string { return v !== null && v > 0 ? `$${v}` : 'TBD'; }

export function OfferBlueprintStep() {
  const serviceId = useOpportunityMapStore((s) => s.serviceId);
  const service = useOfferEngineeringStore((s) => s.service);
  const market = useOfferEngineeringStore((s) => s.market);
  const niche = useOfferEngineeringStore((s) => s.niche);
  const positioning = useOfferEngineeringStore((s) => s.positioning);
  const offerType = useOfferEngineeringStore((s) => s.offerType);
  const deliverables = useOfferEngineeringStore((s) => s.deliverables);
  const uniqueMechanism = useOfferEngineeringStore((s) => s.uniqueMechanism);
  const scopeLimits = useOfferEngineeringStore((s) => s.scopeLimits);
  const valueAmplifier = useOfferEngineeringStore((s) => s.valueAmplifier);
  const pricingModel = useOfferEngineeringStore((s) => s.pricingModel);
  const finalPrice = useOfferEngineeringStore((s) => s.finalPrice);
  const tieredPricing = useOfferEngineeringStore((s) => s.tieredPricing);
  const valueBasedPricing = useOfferEngineeringStore((s) => s.valueBasedPricing);
  const proposalSummary = useOfferEngineeringStore((s) => s.proposalSummary);
  const offerBlueprint = useOfferEngineeringStore((s) => s.offerBlueprint);
  const setOfferBlueprint = useOfferEngineeringStore((s) => s.setOfferBlueprint);
  const confirmStep = useOfferEngineeringStore((s) => s.confirmStep);
  const previousStep = useOfferEngineeringStore((s) => s.previousStep);
  const navigate = useNavigate();
  const [toast, setToast] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }, []);

  const { pathContent } = useModule2ResolvedContent();
  const blueprintAngle = pathContent?.content.blueprintAngle;

  const engineeringData = serviceId ? getEngineeringDataForService(serviceId) : undefined;
  const serviceLabel = engineeringData?.label ?? service ?? 'Your Service';
  const audience = getAudienceLabel(niche || '', market || '');
  const cat = getServiceCategory(serviceId);

  const offerTypeLabel =
    offerType === 'retainer' ? 'retainer'
      : offerType === 'one_time_project' ? 'one_time_project'
      : offerType === 'milestone_based' ? 'milestone_based'
      : 'one_time_project';

  const modelLabel =
    pricingModel === 'flat_rate' ? 'Flat Rate'
      : pricingModel === 'tiered' ? 'Tiered'
      : pricingModel === 'value_based' ? 'Value Based'
      : 'Custom';

  const pricingDesc = pricingModel === 'tiered'
    ? `${p(tieredPricing.starterPrice)} \u2013 ${p(tieredPricing.premiumPrice)}`
    : pricingModel === 'value_based'
      ? valueBasedPricing.suggestedPriceRange || `$${finalPrice}`
      : finalPrice ? `$${finalPrice}` : 'TBD';

  const generatedBlueprint = useMemo((): OfferBlueprint => ({
    productizedService: `${serviceLabel} ${offerTypeLabel === 'retainer' ? 'Retainer' : offerTypeLabel === 'one_time_project' ? 'One-Time Project' : 'Milestone Based'}`,
    offerName: `${serviceLabel} ${offerTypeLabel === 'retainer' ? 'Retainer' : offerTypeLabel === 'one_time_project' ? 'One-Time Project' : 'Milestone Based'}`,
    whoItIsFor: blueprintAngle?.whoItIsFor || generateWhoItIsFor(cat, audience, deliverables, niche),
    problemItSolves: blueprintAngle?.problemItSolves || generateProblemItSolves(cat, audience, serviceLabel, niche),
    corePromise: blueprintAngle?.corePromise || generateCorePromise(cat, serviceLabel, uniqueMechanism, niche),
    deliverables,
    uniqueMechanism: uniqueMechanism || 'A structured delivery system designed for consistency and quality',
    scopeLimits: { ...scopeLimits },
    valueAmplifier: generateNicheValueAmplifier(cat, niche, valueAmplifier || ''),
    timeline: scopeLimits.deliveryTime || 'Per agreed schedule',
    pricingModel,
    finalPrice,
    tieredPricing: { ...tieredPricing },
    valueBasedPricing: { ...valueBasedPricing },
    pricingStructure: `${pricingDesc} \u2014 ${modelLabel}`,
    whyThisWorks: blueprintAngle?.whyThisWorks || generateWhyThisWorks(cat, audience, deliverables, uniqueMechanism, niche),
    nextStepCTA: blueprintAngle?.nextStepCTA || generateNextStepCTA(cat, audience, offerTypeLabel, niche),
    proposalSummary: { ...proposalSummary, deliverables },
  }), [serviceLabel, offerTypeLabel, cat, audience, deliverables, uniqueMechanism, scopeLimits, valueAmplifier, pricingModel, finalPrice, tieredPricing, valueBasedPricing, pricingDesc, modelLabel, positioning, proposalSummary, niche, blueprintAngle]);

  const [editDraft, setEditDraft] = useState<OfferBlueprint | null>(null);
  const draft = editDraft ?? offerBlueprint ?? generatedBlueprint;
  const bp = offerBlueprint ?? generatedBlueprint;

  const handleGenerate = () => {
    setOfferBlueprint(generatedBlueprint);
    setEditDraft(null);
    confirmStep();
  };

  const startEditing = () => {
    setEditDraft({ ...(offerBlueprint ?? generatedBlueprint) });
    setEditing(true);
  };

  const saveEdits = () => {
    if (editDraft) {
      setOfferBlueprint(editDraft);
    }
    setEditing(false);
    showToast('Blueprint updated');
  };

  const updateDraft = <K extends keyof OfferBlueprint>(key: K, value: OfferBlueprint[K]) => {
    setEditDraft((prev) => prev ? { ...prev, [key]: value } : prev);
  };

  const updateDeliverable = (index: number, value: string) => {
    setEditDraft((prev) => {
      if (!prev) return prev;
      const d = [...prev.deliverables];
      d[index] = value;
      return { ...prev, deliverables: d };
    });
  };

  const handleDownloadPDF = useCallback(async () => {
    setPdfLoading(true);
    try {
      const blob = await exportBlueprintPDF(draft, serviceId, market, niche);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const pdfTitle = polishedOfferTitle(draft, serviceId, niche);
      a.download = `${getSlug(pdfTitle)}-offer-blueprint.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast('PDF downloaded');
    } catch {
      showToast('PDF export failed');
    } finally {
      setPdfLoading(false);
    }
  }, [draft, serviceId, market, niche, showToast]);

  const handleDownloadMD = useCallback(() => {
    const markdown = buildMarkdown(draft);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${getSlug(draft.offerName)}-offer-blueprint.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Markdown downloaded');
  }, [draft, showToast]);

  const handleCopy = useCallback(() => {
    const markdown = buildMarkdown(draft);
    navigator.clipboard.writeText(markdown).then(
      () => showToast('Blueprint copied to clipboard'),
      () => showToast('Failed to copy to clipboard'),
    );
  }, [draft, showToast]);

  if (!offerBlueprint) {
    return (
      <div className="space-y-6">
        <div className="space-y-2">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold uppercase tracking-widest mb-1">
            Step 8 of 8
          </span>
          <h2 className="text-3xl font-bold text-[#0b1c30] mb-2">Generate Your Offer Blueprint</h2>
          <p className="text-neutral-500 text-sm leading-relaxed">
            Compile your parameters into a polished productized offer outline.
          </p>
        </div>

        <div className="flex items-start gap-4 p-5 rounded-2xl border border-[#eff4ff] bg-[#eff4ff]/60">
          <span className="flex items-center justify-center w-8 h-8 rounded-xl bg-white border border-[#eff4ff] text-[#0058be] shrink-0 mt-0.5 shadow-sm">
            <FileText size={14} className="text-[#0058be]" />
          </span>
          <div className="space-y-1">
            <p className="text-xs text-neutral-600 leading-relaxed font-medium">
              Review your draft details and compile the final blueprint sheet. Once created, you can customize the copy manually or export directly to PDF/Markdown.
            </p>
          </div>
        </div>

        <BlueprintPreview bp={bp} />

        <div className="flex items-center gap-3 pt-4 border-t border-neutral-200">
          <button
            onClick={previousStep}
            className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
          >
            <ArrowLeft size={14} />
            Back
          </button>

          <button
            onClick={handleGenerate}
            className="inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#0058be] hover:bg-[#0047a0] text-white font-bold text-xs uppercase tracking-wider shadow-sm transition-all cursor-pointer border border-transparent"
          >
            <Download size={14} />
            Generate Blueprint
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold uppercase tracking-widest mb-1">
          Step 8 of 8 — Complete
        </span>
        <h2 className="text-3xl font-bold text-[#0b1c30] mb-2">
          {editing ? 'Edit Blueprint Copy' : 'Offer Blueprint Ready'}
        </h2>
        <p className="text-neutral-500 text-sm leading-relaxed">
          {editing
            ? 'Refine wording directly. Changes will reflect across PDF and Markdown exports.'
            : 'Your productized offer specifications are complete. Review below and export to send to a lead.'}
        </p>
      </div>

      <div className="flex items-center gap-2.5 px-4 py-3 border border-[#eff4ff] bg-[#eff4ff]/60 text-[#0058be] rounded-2xl shadow-sm">
        <Check size={16} className="text-[#0058be] stroke-[3]" />
        <span className="text-xs font-bold">
          Offer configuration finalised — all 8 steps completed
        </span>
      </div>

      {editing ? (
        <BlueprintEditor draft={editDraft!} onChange={setEditDraft} updateDraft={updateDraft} updateDeliverable={updateDeliverable} />
      ) : (
        <BlueprintPreview bp={draft} />
      )}

      {/* Structured Action Toolbar */}
      <div className="flex flex-col gap-5 pt-4 border-t border-neutral-200">
        <div className="flex items-center gap-2.5 flex-wrap">
          {editing ? (
            <button
              onClick={saveEdits}
              className="inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#0058be] hover:bg-[#0047a0] text-white font-bold text-xs uppercase tracking-wider shadow-sm transition-all cursor-pointer"
            >
              <Save size={13} />
              Save Edits
            </button>
          ) : (
            <>
              <button
                onClick={handleDownloadPDF}
                disabled={pdfLoading}
                className="inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#0058be] hover:bg-[#0047a0] text-white font-bold text-xs uppercase tracking-wider shadow-sm transition-all cursor-pointer"
              >
                <FileDown size={13} />
                {pdfLoading ? 'Exporting...' : 'Download PDF'}
              </button>

              <button
                onClick={startEditing}
                className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
              >
                <Edit3 size={11} />
                Edit Text
              </button>

              <button
                onClick={handleCopy}
                className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
              >
                <Copy size={11} />
                Copy Copy
              </button>

              <button
                onClick={handleDownloadMD}
                className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
              >
                <FileText size={11} />
                Markdown
              </button>
            </>
          )}
        </div>

        {!editing && (
          <div className="pt-4 border-t border-neutral-200 flex flex-col gap-2.5">
            <button
              onClick={() => navigate('/workspace/authority-system')}
              className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-[#0b1c30] hover:bg-[#152a45] text-white font-bold text-xs uppercase tracking-wider shadow-md transition-colors cursor-pointer w-full sm:w-auto"
            >
              Continue to Authority System
              <ArrowRight size={14} />
            </button>
            <span className="text-[10px] text-neutral-400 uppercase tracking-widest text-center font-bold">
              Phase 3 — Construct your authority assets & trust signals
            </span>
          </div>
        )}
      </div>

      {toast && (
        <div className="fixed bottom-6 right-6 flex items-center gap-2 px-4 py-3 rounded-xl bg-[#0b1c30] border border-white/10 text-xs text-white shadow-2xl z-50">
          <Check size={12} className="text-[#d1f34d]" />
          {toast}
        </div>
      )}
    </div>
  );
}

/* Inline Editor */
function BlueprintEditor({
  draft,
  updateDraft,
  updateDeliverable,
}: {
  draft: OfferBlueprint;
  onChange: (v: OfferBlueprint) => void;
  updateDraft: <K extends keyof OfferBlueprint>(key: K, value: OfferBlueprint[K]) => void;
  updateDeliverable: (index: number, value: string) => void;
}) {
  const fields: { key: keyof OfferBlueprint; label: string; multiline?: boolean }[] = [
    { key: 'offerName', label: 'Offer Title' },
    { key: 'whoItIsFor', label: 'Who It Is For', multiline: true },
    { key: 'problemItSolves', label: 'Problem Statement', multiline: true },
    { key: 'corePromise', label: 'Core Promise', multiline: true },
    { key: 'timeline', label: 'Project Timeline' },
    { key: 'whyThisWorks', label: 'Why This System Works', multiline: true },
    { key: 'nextStepCTA', label: 'Next Step / CTA Wording', multiline: true },
  ];

  return (
    <div className="rounded-3xl border border-neutral-200 bg-white p-6 space-y-5 shadow-sm">
      <div className="space-y-0.5">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Edit Blueprint Fields</span>
        <p className="text-xs text-neutral-400">
          Refine the language before sending. These changes do not affect store config, only the document output.
        </p>
      </div>

      {fields.map((f) => (
        <div key={f.key} className="space-y-1.5">
          <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">{f.label}</span>
          {f.multiline ? (
            <textarea
              value={String(draft[f.key] ?? '')}
              onChange={(e) => updateDraft(f.key, e.target.value as never)}
              rows={3}
              className="w-full px-4 py-3 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors resize-none leading-relaxed"
            />
          ) : (
            <input
              type="text"
              value={String(draft[f.key] ?? '')}
              onChange={(e) => updateDraft(f.key, e.target.value as never)}
              className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors"
            />
          )}
        </div>
      ))}

      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Deliverables</span>
        {draft.deliverables.map((d, i) => (
          <input
            key={i}
            type="text"
            value={d}
            onChange={(e) => updateDeliverable(i, e.target.value)}
            className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors mb-2"
          />
        ))}
      </div>

      <div className="space-y-1.5">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Pricing Output</span>
        <input
          type="text"
          value={draft.pricingStructure}
          onChange={(e) => updateDraft('pricingStructure', e.target.value)}
          className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors"
        />
      </div>
    </div>
  );
}

/* Document View BlueprintPreview */
function BlueprintPreview({ bp }: { bp: OfferBlueprint }) {
  const initials = bp.whoItIsFor.split(' ').slice(0, 2).map(w => w[0]).join('').toUpperCase();

  return (
    <div className="rounded-3xl border border-neutral-200 bg-white overflow-hidden shadow-md">
      <div className="p-6 border-b border-neutral-100 bg-[#f8f9ff]/50">
        <div className="flex items-start justify-between gap-4">
          <div>
            <span className="text-[9px] font-bold uppercase tracking-widest text-[#0058be]">Document Outline</span>
            <h3 className="text-xl font-bold text-[#0b1c30] tracking-tight mt-1">{bp.offerName}</h3>
          </div>
          {initials && (
            <span className="flex items-center justify-center w-9 h-9 rounded-xl bg-white border border-neutral-200 text-xs font-bold text-[#0058be] shrink-0 shadow-sm">
              {initials}
            </span>
          )}
        </div>
        <p className="text-xs text-neutral-500 mt-3 leading-relaxed">
          {bp.whoItIsFor}
        </p>
      </div>

      <div className="p-6 space-y-5 text-xs">
        <PreviewSection icon={AlertCircle} title="The Problem">
          <p className="text-neutral-500 leading-relaxed font-normal">{bp.problemItSolves}</p>
        </PreviewSection>

        <PreviewSection icon={Target} title="Core Promise">
          <p className="text-neutral-700 leading-relaxed font-semibold">{bp.corePromise}</p>
        </PreviewSection>

        <PreviewSection icon={Package} title="Scope & Deliverables">
          {bp.deliverables.length > 0 ? (
            <div className="flex flex-wrap gap-1.5">
              {bp.deliverables.map((d, i) => (
                <span key={i} className="px-2.5 py-1 rounded-lg bg-[#eff4ff]/60 border border-[#eff4ff] text-[10px] text-[#0058be] font-bold">{d}</span>
              ))}
            </div>
          ) : (
            <p className="text-neutral-400 italic">—</p>
          )}
        </PreviewSection>

        <PreviewSection icon={Lightbulb} title="Unique Mechanism">
          <p className="text-neutral-700 font-semibold">{bp.uniqueMechanism}</p>
        </PreviewSection>

        <PreviewSection icon={Shield} title="Scope SLA & Limits">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-2 bg-[#f8f9ff] border border-neutral-200 p-4 rounded-2xl">
            <ScopeItem label="Revisions SLA" value={`${bp.scopeLimits.revisionCount} rounds allowed`} />
            <ScopeItem label="Review Rounds" value={`${bp.scopeLimits.includedRounds} feedback rounds`} />
            <ScopeItem label="Project Turnaround" value={bp.scopeLimits.deliveryTime || bp.timeline} />
            <ScopeItem label="Response Time" value={bp.scopeLimits.responseTime} />
            <ScopeItem label="Communication Hub" value={bp.scopeLimits.communicationMethod} />
          </div>
        </PreviewSection>

        <PreviewSection icon={Zap} title="Value Bonus / Amplifier">
          <p className="text-neutral-500 leading-relaxed">{bp.valueAmplifier}</p>
        </PreviewSection>

        <PreviewSection icon={DollarSign} title="Pricing & Structure">
          <div className="space-y-3">
            <p className="text-2xl font-bold text-[#0b1c30] tracking-tight">{bp.pricingStructure}</p>
            {bp.pricingModel === 'tiered' && (
              <div className="flex gap-4 text-xs text-neutral-400 border-t border-neutral-100 pt-3">
                <span>Starter: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.starterPrice)}</strong></span>
                <span>Pro: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.proPrice)}</strong></span>
                <span>Premium: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.premiumPrice)}</strong></span>
              </div>
            )}
            {bp.pricingModel === 'value_based' && (
              <div className="flex gap-4 text-xs text-neutral-400 border-t border-neutral-100 pt-3">
                <span>Client Value: <strong className="text-[#0b1c30] font-bold">{p(bp.valueBasedPricing.estimatedClientValue)}</strong></span>
                {bp.valueBasedPricing.impactLevel && <span>Impact: <strong className="text-[#0b1c30] font-bold">{bp.valueBasedPricing.impactLevel}</strong></span>}
              </div>
            )}
          </div>
        </PreviewSection>

        <PreviewSection icon={TrendingUp} title="Why This Approach Works">
          <p className="text-neutral-500 leading-relaxed font-normal">{bp.whyThisWorks}</p>
        </PreviewSection>

        <PreviewSection icon={ArrowRight} title="Next Action" accent>
          <p className="text-neutral-700 font-semibold leading-relaxed">{bp.nextStepCTA}</p>
        </PreviewSection>
      </div>
    </div>
  );
}

function PreviewSection({ icon: Icon, title, children, accent }: { icon: typeof Users; title: string; children: React.ReactNode; accent?: boolean }) {
  return (
    <div className={cn("space-y-1.5", accent && 'p-4 rounded-2xl bg-[#eff4ff]/60 border border-[#eff4ff]')}>
      <div className="flex items-center gap-1.5 text-neutral-400">
        <Icon size={12} className={accent ? 'text-[#0058be]' : 'text-neutral-400'} />
        <span className={cn(
          'text-[9px] font-bold uppercase tracking-wider',
          accent ? 'text-[#0058be]' : 'text-neutral-400',
        )}>{title}</span>
      </div>
      <div className="pl-3.5 border-l border-neutral-200">
        {children}
      </div>
    </div>
  );
}

function ScopeItem({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex items-center justify-between gap-4 py-0.5">
      <span className="text-neutral-400 text-[10px] uppercase font-bold tracking-wider">{label}</span>
      <span className="text-[#0b1c30] font-bold">{value ?? '—'}</span>
    </div>
  );
}
