import { useMemo, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import {
  FileText, Check, Download, ArrowLeft, ArrowRight, Copy,
  Edit3, Save, FileDown, ChevronDown, ShieldCheck, HelpCircle
} from 'lucide-react';
import { useOfferEngineeringStore, getEngineeringDataForService, useModule2ResolvedContent } from '../../lib/offer-engineering';
import { useOpportunityMapStore } from '../../lib/opportunity-map';
import { exportBlueprintPDF, polishedOfferTitle } from '../../lib/offer-engineering/pdf-export';
import { cn } from '../../lib/utils';
import type { OfferBlueprint } from '../../types/offer-engineering';
import { getServiceCategory, getAudienceLabel, generateWhoItIsFor, generateProblemItSolves, generateCorePromise, generateWhyThisWorks, generateNextStepCTA, generateNicheValueAmplifier } from '../../lib/blueprint-content';
import { composeStep8Content } from '../../lib/offer-engineering/personalized-content';
import { RISK_REVERSAL_GUARANTEES, OBJECTION_PREEMPTORS } from '../../lib/offer-engineering/riskReversal';

function buildMarkdown(bp: OfferBlueprint): string {
  const lines: string[] = [
    `# ${bp.offerName}`,
    '',
    `**Productized Service:** ${bp.productizedService}`,
    '',
    '---',
    '',
    '## 1. Who It Is For',
    bp.whoItIsFor,
    '',
    '## 2. Problem It Solves',
    bp.problemItSolves,
    '',
    '## 3. Core Promise',
    bp.corePromise,
    '',
    '## 4. Deliverables',
    ...(bp.deliverables.length > 0 ? bp.deliverables.map((d) => `- ${d}`) : ['—']),
    '',
    '## 5. Unique Mechanism',
    bp.uniqueMechanism,
    '',
    '## 6. Timeline',
    bp.timeline,
    '',
    '## 7. Scope Rules',
    `- Revisions: ${bp.scopeLimits.revisionCount}`,
    `- Feedback Rounds: ${bp.scopeLimits.includedRounds}`,
    `- Delivery: ${bp.scopeLimits.deliveryTime}`,
    `- Response Time: ${bp.scopeLimits.responseTime}`,
    `- Communication: ${bp.scopeLimits.communicationMethod}`,
    '',
    '## 8. Value Amplifier',
    bp.valueAmplifier,
    '',
    '## 9. Pricing',
    bp.pricingStructure,
    ...(bp.pricingModel === 'tiered'
      ? [
          '',
          `- Starter: ${bp.tieredPricing.starterPrice !== null && bp.tieredPricing.starterPrice > 0 ? `$${bp.tieredPricing.starterPrice}` : 'TBD'}`,
          `- Pro: ${bp.tieredPricing.proPrice !== null && bp.tieredPricing.proPrice > 0 ? `$${bp.tieredPricing.proPrice}` : 'TBD'}`,
          `- Premium: ${bp.tieredPricing.premiumPrice !== null && bp.tieredPricing.premiumPrice > 0 ? `$${bp.tieredPricing.premiumPrice}` : 'TBD'}`,
        ]
      : []),
    ...(bp.pricingModel === 'value_based'
      ? [
          '',
          `- Estimated Client Value: ${bp.valueBasedPricing.estimatedClientValue !== null && bp.valueBasedPricing.estimatedClientValue > 0 ? `$${bp.valueBasedPricing.estimatedClientValue}` : 'TBD'}`,
          ...(bp.valueBasedPricing.impactLevel ? [`- Impact: ${bp.valueBasedPricing.impactLevel}`] : []),
        ]
      : []),
    '',
    '## 10. Why This Works',
    bp.whyThisWorks,
    '',
    '## 11. Next Step',
    bp.nextStepCTA,
    '',
    '---',
    '',
    `*Generated by Offer Engineering — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`,
    '',
  ];
  return lines.join('\n');
}

function getSlug(name: string): string {
  return (name || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'offer-blueprint';
}

function p(v: number | null): string { return v !== null && v > 0 ? `$${v}` : 'TBD'; }

export function OfferBlueprintStep() {
  const serviceId = useOpportunityMapStore((s) => s.serviceId);
  const careerTrackId = useOpportunityMapStore((s) => s.careerTrackId);
  const marketId = useOpportunityMapStore((s) => s.marketId);
  const nicheId_ = useOpportunityMapStore((s) => s.nicheId);
  const service = useOfferEngineeringStore((s) => s.service);
  const market = useOfferEngineeringStore((s) => s.market);
  const niche = useOfferEngineeringStore((s) => s.niche);
  const positioning = useOfferEngineeringStore((s) => s.positioning);
  const offerType = useOfferEngineeringStore((s) => s.offerType);
  const deliverables = useOfferEngineeringStore((s) => s.deliverables);
  const uniqueMechanism = useOfferEngineeringStore((s) => s.uniqueMechanism);
  const scopeLimits = useOfferEngineeringStore((s) => s.scopeLimits);
  const valueAmplifier = useOfferEngineeringStore((s) => s.valueAmplifier);
  const pricingModel = useOfferEngineeringStore((s) => s.pricingModel);
  const finalPrice = useOfferEngineeringStore((s) => s.finalPrice);
  const tieredPricing = useOfferEngineeringStore((s) => s.tieredPricing);
  const valueBasedPricing = useOfferEngineeringStore((s) => s.valueBasedPricing);
  const proposalSummary = useOfferEngineeringStore((s) => s.proposalSummary);
  const offerBlueprint = useOfferEngineeringStore((s) => s.offerBlueprint);
  const setOfferBlueprint = useOfferEngineeringStore((s) => s.setOfferBlueprint);
  const confirmStep = useOfferEngineeringStore((s) => s.confirmStep);
  const previousStep = useOfferEngineeringStore((s) => s.previousStep);
  const navigate = useNavigate();
  const [toast, setToast] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [showFullDetail, setShowFullDetail] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);

  const personalized = useMemo(
    () => composeStep8Content({
      careerTrackId,
      serviceId,
      marketId,
      nicheId: nicheId_,
      offerType,
      deliverables,
      uniqueMechanism,
      scopeLimits,
      valueAmplifier,
      pricingModel,
      finalPrice,
    }),
    [careerTrackId, serviceId, marketId, nicheId_, offerType, deliverables, uniqueMechanism, scopeLimits, valueAmplifier, pricingModel, finalPrice],
  );

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }, []);

  const { pathContent } = useModule2ResolvedContent();
  const blueprintAngle = pathContent?.content.blueprintAngle;

  const engineeringData = serviceId ? getEngineeringDataForService(serviceId) : undefined;
  const serviceLabel = engineeringData?.label ?? service ?? 'Your Service';
  const audience = getAudienceLabel(niche || '', market || '');
  const cat = getServiceCategory(serviceId);

  const offerTypeLabel =
    offerType === 'retainer' ? 'retainer'
      : offerType === 'one_time_project' ? 'one_time_project'
      : offerType === 'milestone_based' ? 'milestone_based'
      : 'one_time_project';

  const offerTypeDisplay =
    offerType === 'retainer' ? 'Retainer'
      : offerType === 'one_time_project' ? 'One-Time Project'
      : offerType === 'milestone_based' ? 'Milestone Based'
      : 'One-Time Project';

  const modelLabel =
    pricingModel === 'flat_rate' ? 'Flat Rate'
      : pricingModel === 'tiered' ? 'Tiered'
      : pricingModel === 'value_based' ? 'Value Based'
      : 'Custom';

  const pricingDesc = pricingModel === 'tiered'
    ? `${p(tieredPricing.starterPrice)} \u2013 ${p(tieredPricing.premiumPrice)}`
    : pricingModel === 'value_based'
      ? valueBasedPricing.suggestedPriceRange || `$${finalPrice}`
      : finalPrice ? `$${finalPrice}` : 'TBD';

  const generatedBlueprint = useMemo((): OfferBlueprint => ({
    productizedService: `${serviceLabel} ${offerTypeLabel === 'retainer' ? 'Retainer' : offerTypeLabel === 'one_time_project' ? 'One-Time Project' : 'Milestone Based'}`,
    offerName: `${serviceLabel} ${offerTypeLabel === 'retainer' ? 'Retainer' : offerTypeLabel === 'one_time_project' ? 'One-Time Project' : 'Milestone Based'}`,
    whoItIsFor: blueprintAngle?.whoItIsFor || generateWhoItIsFor(cat, audience, deliverables, niche),
    problemItSolves: blueprintAngle?.problemItSolves || generateProblemItSolves(cat, audience, serviceLabel, niche),
    corePromise: blueprintAngle?.corePromise || generateCorePromise(cat, serviceLabel, uniqueMechanism, niche),
    deliverables,
    uniqueMechanism: uniqueMechanism || 'A structured delivery system designed for consistency and quality',
    scopeLimits: { ...scopeLimits },
    valueAmplifier: generateNicheValueAmplifier(cat, niche, valueAmplifier || ''),
    timeline: scopeLimits.deliveryTime || 'Per agreed schedule',
    pricingModel,
    finalPrice,
    tieredPricing: { ...tieredPricing },
    valueBasedPricing: { ...valueBasedPricing },
    pricingStructure: `${pricingDesc} \u2014 ${modelLabel}`,
    whyThisWorks: blueprintAngle?.whyThisWorks || generateWhyThisWorks(cat, audience, deliverables, uniqueMechanism, niche),
    nextStepCTA: blueprintAngle?.nextStepCTA || generateNextStepCTA(cat, audience, offerTypeLabel, niche),
    proposalSummary: { ...proposalSummary, deliverables },
  }), [serviceLabel, offerTypeLabel, cat, audience, deliverables, uniqueMechanism, scopeLimits, valueAmplifier, pricingModel, finalPrice, tieredPricing, valueBasedPricing, pricingDesc, modelLabel, positioning, proposalSummary, niche, blueprintAngle]);

  const [editDraft, setEditDraft] = useState<OfferBlueprint | null>(null);
  const draft = editDraft ?? offerBlueprint ?? generatedBlueprint;
  const bp = offerBlueprint ?? generatedBlueprint;

  const handleGenerate = () => {
    setOfferBlueprint(generatedBlueprint, 'auto_generated');
    setEditDraft(null);
    confirmStep();
  };

  const startEditing = () => {
    setEditDraft({ ...(offerBlueprint ?? generatedBlueprint) });
    setEditing(true);
  };

  const saveEdits = () => {
    if (editDraft) {
      setOfferBlueprint(editDraft, 'user_edited');
    }
    setEditing(false);
    showToast('Blueprint updated');
  };

  const updateDraft = <K extends keyof OfferBlueprint>(key: K, value: OfferBlueprint[K]) => {
    setEditDraft((prev) => prev ? { ...prev, [key]: value } : prev);
  };

  const updateDeliverable = (index: number, value: string) => {
    setEditDraft((prev) => {
      if (!prev) return prev;
      const d = [...prev.deliverables];
      d[index] = value;
      return { ...prev, deliverables: d };
    });
  };

  const handleDownloadPDF = useCallback(async () => {
    setPdfLoading(true);
    try {
      const blob = await exportBlueprintPDF(draft, serviceId, market, niche);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const pdfTitle = polishedOfferTitle(draft, serviceId, niche);
      a.download = `${getSlug(pdfTitle)}-offer-blueprint.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast('PDF downloaded');
    } catch {
      showToast('PDF export failed');
    } finally {
      setPdfLoading(false);
    }
  }, [draft, serviceId, market, niche, showToast]);

  const handleDownloadMD = useCallback(() => {
    const markdown = buildMarkdown(draft);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${getSlug(draft.offerName)}-offer-blueprint.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Markdown downloaded');
  }, [draft, showToast]);

  const handleCopy = useCallback(() => {
    const markdown = buildMarkdown(draft);
    navigator.clipboard.writeText(markdown).then(
      () => showToast('Blueprint copied to clipboard'),
      () => showToast('Failed to copy to clipboard'),
    );
  }, [draft, showToast]);

  if (!offerBlueprint) {
    return (
      <div className="space-y-6">
        <div className="space-y-2">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold uppercase tracking-widest mb-1">
            Step 8 of 8
          </span>
          <h2 className="text-3xl font-bold text-[#0b1c30] mb-2">Generate Your Offer Blueprint</h2>
          <p className="text-neutral-500 text-sm leading-relaxed">
            Compile your parameters into a polished productized offer outline.
          </p>
        </div>

        <div className="flex items-start gap-4 p-5 rounded-2xl border border-[#eff4ff] bg-[#eff4ff]/60">
          <span className="flex items-center justify-center w-8 h-8 rounded-xl bg-white border border-[#eff4ff] text-[#0058be] shrink-0 mt-0.5 shadow-sm">
            <FileText size={14} className="text-[#0058be]" />
          </span>
          <div className="space-y-1">
            <p className="text-xs text-neutral-600 leading-relaxed font-medium">
              {personalized.executionGuidance}
            </p>
          </div>
        </div>

        <BlueprintPreview bp={bp} offerTypeDisplay={offerTypeDisplay} pricingModelDisplay={modelLabel} marketDisplay={audience} />

        <div className="flex items-center gap-3 pt-4 border-t border-neutral-200">
          <button
            onClick={previousStep}
            className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
          >
            <ArrowLeft size={14} />
            Back
          </button>

          <button
            onClick={handleGenerate}
            className="inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#0058be] hover:bg-[#0047a0] text-white font-bold text-xs uppercase tracking-wider shadow-sm transition-all cursor-pointer border border-transparent"
          >
            <Download size={14} />
            Generate Blueprint
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold uppercase tracking-widest mb-1">
          Step 8 of 8 — Complete
        </span>
        <h2 className="text-3xl font-bold text-[#0b1c30] mb-2">
          {editing ? 'Edit Blueprint Copy' : 'Offer Blueprint Ready'}
        </h2>
        <p className="text-neutral-500 text-sm leading-relaxed">
          {editing
            ? 'Refine wording directly. Changes will reflect across PDF and Markdown exports.'
            : 'Your productized offer specifications are complete. Review below and export to send to a lead.'}
        </p>
      </div>

      <div className="flex items-center gap-2.5 px-4 py-3 border border-[#eff4ff] bg-[#eff4ff]/60 text-[#0058be] rounded-2xl shadow-sm">
        <Check size={16} className="text-[#0058be] stroke-[3]" />
        <span className="text-xs font-bold">
          Offer configuration finalised — all 8 steps completed
        </span>
      </div>

      {editing ? (
        <BlueprintEditor draft={editDraft!} onChange={setEditDraft} updateDraft={updateDraft} updateDeliverable={updateDeliverable} />
      ) : (
        <>
          <BlueprintPreview bp={draft} offerTypeDisplay={offerTypeDisplay} pricingModelDisplay={modelLabel} marketDisplay={audience} />
          <div className="rounded-2xl border border-neutral-200 bg-white overflow-hidden">
            <button
              onClick={() => setShowFullDetail(!showFullDetail)}
              className="w-full flex items-center justify-between gap-3 px-5 py-3 text-left hover:bg-neutral-50 transition-colors cursor-pointer"
            >
              <span className="flex items-center gap-2 text-xs font-bold text-neutral-600 uppercase tracking-wider">
                <FileText size={13} className="text-neutral-600" />
                View full blueprint
              </span>
              <span className={cn(
                'transition-transform duration-200 text-neutral-500',
                showFullDetail && 'rotate-180'
              )}>
                <ChevronDown size={14} />
              </span>
            </button>
            {showFullDetail && (
              <div className="border-t border-neutral-200 p-5 space-y-3">
                <BlueprintFullDetail bp={draft} />
              </div>
            )}
          </div>
        </>
      )}

      {/* Structured Action Toolbar */}
      <div className="flex flex-col gap-5 pt-4 border-t border-neutral-200">
        <div className="flex items-center gap-2.5 flex-wrap">
          {editing ? (
            <button
              onClick={saveEdits}
              className="inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-[#0058be] hover:bg-[#0047a0] text-white font-bold text-xs uppercase tracking-wider shadow-sm transition-all cursor-pointer"
            >
              <Save size={13} />
              Save Edits
            </button>
          ) : (
            <>
              <button
                onClick={startEditing}
                className="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
              >
                <Edit3 size={11} />
                Edit
              </button>

              <button
                onClick={handleCopy}
                className="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
              >
                <Copy size={11} />
                Copy Blueprint
              </button>

              <div className="relative">
                <button
                  onClick={() => setShowExportMenu(!showExportMenu)}
                  disabled={pdfLoading}
                  className="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-xl border border-neutral-200 bg-white text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-all font-bold text-xs uppercase tracking-wider shadow-sm cursor-pointer"
                >
                  <FileDown size={11} />
                  {pdfLoading ? 'Exporting...' : 'Export'}
                  {!pdfLoading && (
                    <ChevronDown size={10} className="text-neutral-400" />
                  )}
                </button>
                {showExportMenu && (
                  <div className="absolute top-full left-0 mt-1 w-44 rounded-xl border border-neutral-200 bg-white shadow-lg z-20 overflow-hidden">
                    <button
                      onClick={() => { handleDownloadPDF(); setShowExportMenu(false); }}
                      className="w-full flex items-center gap-2 px-4 py-2.5 text-xs font-bold text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-colors cursor-pointer"
                    >
                      <FileDown size={11} className="text-neutral-400" />
                      Download PDF
                    </button>
                    <button
                      onClick={() => { handleDownloadMD(); setShowExportMenu(false); }}
                      className="w-full flex items-center gap-2 px-4 py-2.5 text-xs font-bold text-neutral-500 hover:text-neutral-800 hover:bg-neutral-50 transition-colors cursor-pointer border-t border-neutral-100"
                    >
                      <FileText size={11} className="text-neutral-400" />
                      Markdown
                    </button>
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {!editing && (
          <>
            <div className="rounded-2xl border border-[#eff4ff] bg-[#eff4ff]/60 p-4 space-y-1">
              <span className="block text-[9px] font-bold uppercase tracking-wider text-[#0058be]">Next Step</span>
              <p className="text-xs text-neutral-600 font-medium">{personalized.reviewGuidance}</p>
              <p className="text-[11px] text-neutral-500 mt-0.5">{personalized.nextActionHelper}</p>
            </div>
            <div className="pt-4 border-t border-neutral-200">
              <button
                onClick={() => navigate('/workspace/authority-system')}
                className="w-full inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl bg-[#0b1c30] hover:bg-[#152a45] text-white font-bold text-sm uppercase tracking-wider shadow-md transition-colors cursor-pointer"
              >
                Continue to Authority System
                <ArrowRight size={14} />
              </button>
              <p className="text-[10px] text-neutral-500 text-center mt-1.5 leading-relaxed">
                Next: Build proof assets and authority signals.
              </p>
            </div>
          </>
        )}
      </div>

      {toast && (
        <div className="fixed bottom-6 right-6 flex items-center gap-2 px-4 py-3 rounded-xl bg-[#0b1c30] border border-white/10 text-xs text-white shadow-2xl z-50">
          <Check size={12} className="text-[#d1f34d]" />
          {toast}
        </div>
      )}
    </div>
  );
}

/* Inline Editor */
function BlueprintEditor({
  draft,
  updateDraft,
  updateDeliverable,
}: {
  draft: OfferBlueprint;
  onChange: (v: OfferBlueprint) => void;
  updateDraft: <K extends keyof OfferBlueprint>(key: K, value: OfferBlueprint[K]) => void;
  updateDeliverable: (index: number, value: string) => void;
}) {
  const fields: { key: keyof OfferBlueprint; label: string; multiline?: boolean }[] = [
    { key: 'offerName', label: 'Offer Title' },
    { key: 'whoItIsFor', label: 'Who It Is For', multiline: true },
    { key: 'problemItSolves', label: 'Problem Statement', multiline: true },
    { key: 'corePromise', label: 'Core Promise', multiline: true },
    { key: 'timeline', label: 'Project Timeline' },
    { key: 'whyThisWorks', label: 'Why This System Works', multiline: true },
    { key: 'nextStepCTA', label: 'Next Step / CTA Wording', multiline: true },
  ];

  return (
    <div className="rounded-3xl border border-neutral-200 bg-white p-6 space-y-5 shadow-sm">
      <div className="space-y-0.5">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Edit Blueprint Fields</span>
        <p className="text-xs text-neutral-400">
          Refine the language before sending. These changes do not affect store config, only the document output.
        </p>
      </div>

      {fields.map((f) => (
        <div key={f.key} className="space-y-1.5">
          <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">{f.label}</span>
          {f.multiline ? (
            <textarea
              value={String(draft[f.key] ?? '')}
              onChange={(e) => updateDraft(f.key, e.target.value as never)}
              rows={3}
              className="w-full px-4 py-3 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors resize-none leading-relaxed"
            />
          ) : (
            <input
              type="text"
              value={String(draft[f.key] ?? '')}
              onChange={(e) => updateDraft(f.key, e.target.value as never)}
              className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors"
            />
          )}
        </div>
      ))}

      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Deliverables</span>
        {draft.deliverables.map((d, i) => (
          <input
            key={i}
            type="text"
            value={d}
            onChange={(e) => updateDeliverable(i, e.target.value)}
            className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors mb-2"
          />
        ))}
      </div>

      <div className="space-y-1.5">
        <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Pricing Output</span>
        <input
          type="text"
          value={draft.pricingStructure}
          onChange={(e) => updateDraft('pricingStructure', e.target.value)}
          className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors"
        />
      </div>
    </div>
  );
}

/* ── Dashboard helpers ── */

function ClampedText({ text, textClass }: { text: string; textClass?: string }) {
  const [expanded, setExpanded] = useState(false);
  const isLong = text.length > 80;

  return (
    <div>
      <p className={cn('text-sm leading-relaxed', textClass || 'text-neutral-600', !expanded && 'line-clamp-2')}>
        {text}
      </p>
      {isLong && (
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-[10px] font-bold text-[#0058be] hover:text-[#0047a0] mt-1 cursor-pointer"
        >
          {expanded ? 'Show less' : 'View reasoning \u2192'}
        </button>
      )}
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="px-6 py-4">
      <span className="block text-[9px] font-bold uppercase tracking-wider text-neutral-400 mb-1">{label}</span>
      <span className="block text-sm font-bold text-[#0b1c30]">{value}</span>
    </div>
  );
}

function DashboardSection({ title, children, accent }: { title: string; children: React.ReactNode; accent?: boolean }) {
  return (
    <div className={cn('rounded-2xl border p-4', accent ? 'bg-[#eff4ff]/60 border-[#eff4ff]' : 'bg-white border-neutral-200 shadow-sm')}>
      <span className={cn('block text-[9px] font-bold uppercase tracking-wider mb-2', accent ? 'text-[#0058be]' : 'text-neutral-400')}>
        {title}
      </span>
      {children}
    </div>
  );
}

/* ── Dashboard-style BlueprintPreview ── */

function BlueprintPreview({
  bp,
  offerTypeDisplay,
  pricingModelDisplay,
  marketDisplay,
}: {
  bp: OfferBlueprint;
  offerTypeDisplay?: string;
  pricingModelDisplay?: string;
  marketDisplay?: string;
}) {
  const deliverablesCount = bp.deliverables.length;
  const revisionRounds = `${bp.scopeLimits.revisionCount} round${bp.scopeLimits.revisionCount !== 1 ? 's' : ''}`;
  const turnaround = bp.scopeLimits.deliveryTime || bp.timeline || 'Per agreed schedule';
  const isPriceTBD =
    (bp.tieredPricing.starterPrice === null || bp.tieredPricing.starterPrice <= 0) &&
    (bp.tieredPricing.proPrice === null || bp.tieredPricing.proPrice <= 0) &&
    (bp.tieredPricing.premiumPrice === null || bp.tieredPricing.premiumPrice <= 0) &&
    (bp.valueBasedPricing.estimatedClientValue === null || bp.valueBasedPricing.estimatedClientValue <= 0) &&
    (bp.finalPrice === null || bp.finalPrice <= 0);

  return (
    <div className="space-y-5">
      {/* Header Card */}
      <div className="rounded-3xl border border-neutral-200 bg-white overflow-hidden shadow-sm">
        <div className="p-6 sm:p-8">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#d1f34d]/20 text-[#0b1c30] text-[9px] font-extrabold uppercase tracking-widest mb-3">
            <Check size={10} className="text-[#0b1c30]" strokeWidth={3} />
            Your Offer Is Ready
          </span>
          <h3 className="text-2xl sm:text-3xl font-bold text-[#0b1c30] tracking-tight mb-2">{bp.offerName}</h3>
          <p className="text-sm text-neutral-500 leading-relaxed">{bp.whoItIsFor}</p>
          <div className="flex flex-wrap gap-2 mt-4">
            {offerTypeDisplay && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-[#eff4ff] border border-[#eff4ff] text-[10px] font-bold text-[#0058be]">
                {offerTypeDisplay}
              </span>
            )}
            {pricingModelDisplay && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-[#eff4ff] border border-[#eff4ff] text-[10px] font-bold text-[#0058be]">
                {pricingModelDisplay}
              </span>
            )}
            {marketDisplay && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-[#eff4ff] border border-[#eff4ff] text-[10px] font-bold text-[#0058be]">
                {marketDisplay}
              </span>
            )}
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 divide-y sm:divide-y-0 sm:divide-x divide-neutral-100 border-t border-neutral-100">
          <StatCard label="Deliverables" value={`${deliverablesCount} item${deliverablesCount !== 1 ? 's' : ''}`} />
          <StatCard label="Revisions" value={revisionRounds} />
          <StatCard label="Turnaround" value={turnaround} />
        </div>
      </div>

      {/* Offer Summary */}
      {bp.problemItSolves && (
        <DashboardSection title="Offer Summary">
          <p className="text-sm text-neutral-600 leading-relaxed">{bp.problemItSolves}</p>
        </DashboardSection>
      )}

      {/* Core Promise */}
      {bp.corePromise && (
        <DashboardSection title="Core Promise">
          <p className="text-sm text-[#0b1c30] font-semibold leading-relaxed">{bp.corePromise}</p>
        </DashboardSection>
      )}

      {/* Deliverables */}
      {bp.deliverables.length > 0 && (
        <DashboardSection title="Deliverables">
          <div className="space-y-2">
            {bp.deliverables.map((d, i) => (
              <div key={i} className="flex items-center gap-3 p-3 rounded-xl bg-neutral-50 border border-neutral-100">
                <span className="flex items-center justify-center w-6 h-6 rounded-lg bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold shrink-0">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <span className="text-xs font-semibold text-[#0b1c30]">{d}</span>
              </div>
            ))}
          </div>
        </DashboardSection>
      )}

      {/* Unique Mechanism */}
      {bp.uniqueMechanism && (
        <DashboardSection title="Your Unique Mechanism" accent>
          <p className="text-sm font-bold text-[#0b1c30]">{bp.uniqueMechanism}</p>
        </DashboardSection>
      )}

      {/* Scope & Working Style */}
      <DashboardSection title="Scope & Working Style">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3">
          <div className="flex items-center justify-between gap-4 py-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Turnaround</span>
            <span className="text-xs font-bold text-[#0b1c30]">{turnaround}</span>
          </div>
          <div className="flex items-center justify-between gap-4 py-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Revisions</span>
            <span className="text-xs font-bold text-[#0b1c30]">{revisionRounds}</span>
          </div>
          <div className="flex items-center justify-between gap-4 py-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Feedback Rounds</span>
            <span className="text-xs font-bold text-[#0b1c30]">{bp.scopeLimits.includedRounds} rounds</span>
          </div>
          <div className="flex items-center justify-between gap-4 py-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Communication</span>
            <span className="text-xs font-bold text-[#0b1c30]">{bp.scopeLimits.communicationMethod || '—'}</span>
          </div>
          <div className="flex items-center justify-between gap-4 py-1">
            <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-400">Response Time</span>
            <span className="text-xs font-bold text-[#0b1c30]">{bp.scopeLimits.responseTime || '—'}</span>
          </div>
        </div>
      </DashboardSection>

      {/* Value Amplifier */}
      {bp.valueAmplifier && (
        <DashboardSection title="Value Amplifier" accent>
          <p className="text-sm text-neutral-600 leading-relaxed">{bp.valueAmplifier}</p>
        </DashboardSection>
      )}

      {/* Pricing */}
      <DashboardSection title="Pricing">
        {isPriceTBD ? (
          <>
            <p className="text-xl sm:text-2xl font-bold text-[#0b1c30] tracking-tight">TBD</p>
            <p className="text-[10px] text-neutral-400 mt-0.5">
              {bp.pricingModel === 'flat_rate' ? 'Flat Rate'
                : bp.pricingModel === 'tiered' ? 'Tiered'
                : bp.pricingModel === 'value_based' ? 'Value Based'
                : 'Custom'} pricing
            </p>
          </>
        ) : (
          <>
            <p className="text-xl sm:text-2xl font-bold text-[#0b1c30] tracking-tight">{bp.pricingStructure}</p>
            {bp.pricingModel === 'tiered' && (
              <div className="flex flex-wrap gap-3 mt-1.5 text-xs text-neutral-500">
                <span>Starter: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.starterPrice)}</strong></span>
                <span>Pro: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.proPrice)}</strong></span>
                <span>Premium: <strong className="text-[#0b1c30] font-bold">{p(bp.tieredPricing.premiumPrice)}</strong></span>
              </div>
            )}
            {bp.pricingModel === 'value_based' && (
              <div className="flex flex-wrap gap-3 mt-1.5 text-xs text-neutral-500">
                <span>Client Value: <strong className="text-[#0b1c30] font-bold">{p(bp.valueBasedPricing.estimatedClientValue)}</strong></span>
                {bp.valueBasedPricing.impactLevel && <span>Impact: <strong className="text-[#0b1c30] font-bold">{bp.valueBasedPricing.impactLevel}</strong></span>}
              </div>
            )}
            {bp.pricingModel === 'flat_rate' && bp.finalPrice !== null && (
              <p className="text-xs text-neutral-400 mt-0.5">Single price for the entire mapped scope.</p>
            )}
          </>
        )}
      </DashboardSection>

      {/* Why This Works */}
      {bp.whyThisWorks && (
        <DashboardSection title="Why This Works">
          <ClampedText text={bp.whyThisWorks} />
        </DashboardSection>
      )}

      {/* Risk-Reversal Guarantees */}
      <DashboardSection title="Risk-Reversal & Guarantee Options" accent>
        <div className="space-y-3">
          <p className="text-xs text-neutral-500">
            Select a high-converting guarantee clause to include in your client proposals:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {RISK_REVERSAL_GUARANTEES.map((g) => (
              <div key={g.id} className="p-3.5 rounded-2xl bg-white border border-neutral-200/80 shadow-xs space-y-1.5 flex flex-col justify-between">
                <div>
                  <div className="flex items-center gap-1.5 text-[#0058be] font-bold text-xs">
                    <ShieldCheck size={14} />
                    {g.name}
                  </div>
                  <p className="text-[11px] font-semibold text-neutral-800 mt-1">{g.tagline}</p>
                  <p className="text-[10px] text-neutral-500 mt-1 leading-relaxed">{g.description}</p>
                </div>
                <div className="pt-2 border-t border-neutral-100 mt-2">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-neutral-400">Best For: </span>
                  <span className="text-[10px] text-neutral-600 font-medium">{g.bestFor}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </DashboardSection>

      {/* Objection Preemption Battlecards */}
      <DashboardSection title="Client Objection Preemptors">
        <div className="space-y-2.5">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {OBJECTION_PREEMPTORS.map((obj, i) => (
              <div key={i} className="p-3.5 rounded-2xl bg-neutral-50 border border-neutral-100 space-y-1.5">
                <div className="flex items-start gap-2">
                  <HelpCircle size={13} className="text-[#0058be] shrink-0 mt-0.5" />
                  <span className="text-xs font-bold text-[#0b1c30]">{obj.objection}</span>
                </div>
                <div className="pl-5 space-y-1">
                  <span className="text-[9px] font-bold uppercase tracking-wider text-emerald-600 block">{obj.reframe}</span>
                  <p className="text-[11px] text-neutral-600 leading-relaxed">{obj.battlecardResponse}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </DashboardSection>

      {/* Next Action */}
      {bp.nextStepCTA && (
        <div className="rounded-2xl border border-[#eff4ff] bg-[#eff4ff]/60 p-4">
          <span className="block text-[9px] font-bold uppercase tracking-wider text-[#0058be] mb-1">Next Action</span>
          <ClampedText text={bp.nextStepCTA} textClass="text-[#0b1c30] font-semibold" />
        </div>
      )}
    </div>
  );
}

/* ── Full-detail document view inside collapsible ── */

function BlueprintFullDetail({ bp }: { bp: OfferBlueprint }) {
  const sections: { label: string; value: string | null | undefined }[] = [
    { label: 'Offer Name', value: bp.offerName },
    { label: 'Productized Service', value: bp.productizedService },
    { label: 'Who It Is For', value: bp.whoItIsFor },
    { label: 'Problem It Solves', value: bp.problemItSolves },
    { label: 'Core Promise', value: bp.corePromise },
    { label: 'Deliverables', value: bp.deliverables.map((d, i) => `${i + 1}. ${d}`).join('\n') },
    { label: 'Unique Mechanism', value: bp.uniqueMechanism },
    {
      label: 'Scope & Limits',
      value: `Revisions: ${bp.scopeLimits.revisionCount} rounds · Feedback: ${bp.scopeLimits.includedRounds} rounds · Turnaround: ${bp.scopeLimits.deliveryTime || bp.timeline || '—'} · Response: ${bp.scopeLimits.responseTime || '—'} · Communication: ${bp.scopeLimits.communicationMethod || '—'}`,
    },
    { label: 'Value Amplifier', value: bp.valueAmplifier },
    { label: 'Pricing Structure', value: bp.pricingStructure },
    { label: 'Why This Works', value: bp.whyThisWorks },
    { label: 'Next Action', value: bp.nextStepCTA },
  ];

  return (
    <div className="space-y-3">
      {sections.map(
        (s) =>
          s.value && (
            <div key={s.label} className="space-y-0.5">
              <span className="text-[9px] font-bold uppercase tracking-wider text-neutral-400">{s.label}</span>
              <p className="text-xs text-[#0b1c30] leading-relaxed whitespace-pre-wrap">{s.value}</p>
            </div>
          ),
      )}
    </div>
  );
}
