import { useMemo, useEffect, useState, useCallback } from 'react';
import { Package, Shuffle } from 'lucide-react';
import { useOfferEngineeringStore, getEngineeringDataForService } from '../../lib/offer-engineering';
import { useOpportunityMapStore } from '../../lib/opportunity-map';
import { cn } from '../../lib/utils';
import { getServiceCategory, getAudienceLabel, generateProposalVariations } from '../../lib/blueprint-content';

type StringField = 'headline' | 'problem' | 'solution' | 'timeline' | 'pricing' | 'nextSteps';

interface VariantPool {
  headlines: string[];
  problems: string[];
  solutions: string[];
  nextSteps: string[];
}

function getVariationPool(cat: 'video' | 'wordpress' | 'design', niche: string): VariantPool {
  return generateProposalVariations(cat, '', '', '', '', niche);
}

export function ProposalSummaryStep() {
  const serviceId = useOpportunityMapStore((s) => s.serviceId);
  const service = useOfferEngineeringStore((s) => s.service);
  const market = useOfferEngineeringStore((s) => s.market);
  const niche = useOfferEngineeringStore((s) => s.niche);
  const deliverables = useOfferEngineeringStore((s) => s.deliverables);
  const uniqueMechanism = useOfferEngineeringStore((s) => s.uniqueMechanism);
  const scopeLimits = useOfferEngineeringStore((s) => s.scopeLimits);
  const pricingModel = useOfferEngineeringStore((s) => s.pricingModel);
  const finalPrice = useOfferEngineeringStore((s) => s.finalPrice);
  const tieredPricing = useOfferEngineeringStore((s) => s.tieredPricing);
  const offerType = useOfferEngineeringStore((s) => s.offerType);
  const proposalSummary = useOfferEngineeringStore((s) => s.proposalSummary);
  const setProposalSummary = useOfferEngineeringStore((s) => s.setProposalSummary);
  const nextStep = useOfferEngineeringStore((s) => s.nextStep);
  const [variantIndex, setVariantIndex] = useState(0);

  const engineeringData = useMemo(
    () => (serviceId ? getEngineeringDataForService(serviceId) : undefined),
    [serviceId],
  );

  const cat = getServiceCategory(serviceId);
  const audience = getAudienceLabel(niche || '', market || '');
  const serviceLabel = engineeringData?.label ?? service ?? 'Your Service';

  const offerTypeLabel = offerType || 'one_time_project';

  const modelLabel =
    pricingModel === 'flat_rate' ? 'Flat Rate'
      : pricingModel === 'tiered' ? 'Tiered'
      : pricingModel === 'value_based' ? 'Value Based'
      : 'Custom';

  const pricingDesc = pricingModel === 'tiered'
    ? `$${tieredPricing.starterPrice}–$${tieredPricing.premiumPrice} (${modelLabel})`
    : finalPrice ? `$${finalPrice} (${modelLabel})` : `${modelLabel}`;

  const pool = getVariationPool(cat, niche);
  const varCount = pool
    ? Math.max(pool.headlines.length, pool.problems.length, pool.solutions.length, pool.nextSteps.length)
    : 1;
  const vi = variantIndex % varCount;

  const pickVar = useCallback(<T,>(arr: T[], idx: number, fallback: T): T => {
    return arr.length > 0 ? arr[idx % arr.length] : fallback;
  }, []);

  const autoGenerated = useMemo(() => {
    const fullPool = generateProposalVariations(cat, audience, serviceLabel, offerTypeLabel, uniqueMechanism || '', niche);
    return {
      headline: pickVar(fullPool.headlines, vi, `${serviceLabel} for ${audience}`),
      problem: pickVar(fullPool.problems, vi, `${audience} need a better approach to ${serviceLabel.toLowerCase()}.`),
      solution: pickVar(fullPool.solutions, vi, `This package delivers ${deliverables.length > 0 ? deliverables.slice(0, 3).join(', ') + ', and more' : 'a complete service'}${uniqueMechanism ? ` using ${uniqueMechanism}` : ''}.`),
      timeline: scopeLimits.deliveryTime || 'Ongoing per agreed schedule',
      pricing: pricingDesc,
      nextSteps: pickVar(fullPool.nextSteps, vi, `Schedule a short discovery call to discuss your goals and customise this package.`),
    };
  }, [cat, audience, serviceLabel, offerTypeLabel, uniqueMechanism, niche, vi, pickVar, deliverables, scopeLimits.deliveryTime, pricingDesc]);

  // Handle pre-filling fields
  useEffect(() => {
    const ps = proposalSummary;
    const updates: Partial<typeof ps> = {};
    if (!ps.headline.trim()) updates.headline = autoGenerated.headline;
    if (!ps.problem.trim()) updates.problem = autoGenerated.problem;
    if (!ps.solution.trim()) updates.solution = autoGenerated.solution;
    if (!ps.timeline.trim()) updates.timeline = autoGenerated.timeline;
    if (!ps.pricing.trim()) updates.pricing = autoGenerated.pricing;
    if (!ps.nextSteps.trim()) updates.nextSteps = autoGenerated.nextSteps;
    if (Object.keys(updates).length > 0) {
      setProposalSummary({ ...ps, ...updates });
    }
  }, [autoGenerated, proposalSummary, setProposalSummary]);

  const regenerateVariant = useCallback(() => {
    const nextIdx = (variantIndex + 1) % varCount;
    setVariantIndex(nextIdx);
    const gen = {
      headline: pool ? pickVar(pool.headlines, nextIdx, autoGenerated.headline) : autoGenerated.headline,
      problem: pool ? pickVar(pool.problems, nextIdx, autoGenerated.problem) : autoGenerated.problem,
      solution: pool ? pickVar(pool.solutions, nextIdx, autoGenerated.solution) : autoGenerated.solution,
      timeline: autoGenerated.timeline,
      pricing: autoGenerated.pricing,
      nextSteps: pool ? pickVar(pool.nextSteps, nextIdx, autoGenerated.nextSteps) : autoGenerated.nextSteps,
    };
    setProposalSummary({ ...proposalSummary, ...gen });
  }, [variantIndex, varCount, pool, pickVar, autoGenerated, proposalSummary, setProposalSummary]);

  const placeholders = useMemo(() => ({
    headline: autoGenerated.headline,
    problem: autoGenerated.problem,
    solution: autoGenerated.solution,
    timeline: autoGenerated.timeline,
    pricing: autoGenerated.pricing,
    nextSteps: autoGenerated.nextSteps,
  }), [autoGenerated]);

  const isEmpty =
    proposalSummary.headline.trim().length === 0 ||
    proposalSummary.problem.trim().length === 0 ||
    proposalSummary.solution.trim().length === 0 ||
    proposalSummary.timeline.trim().length === 0 ||
    proposalSummary.pricing.trim().length === 0 ||
    proposalSummary.nextSteps.trim().length === 0;

  const update = (field: StringField, value: string) => {
    setProposalSummary({ ...proposalSummary, [field]: value });
  };

  const stringFields: { key: StringField; label: string; multiline?: boolean }[] = [
    { key: 'headline', label: 'Proposal Title / Headline' },
    { key: 'problem', label: 'The Problem Statement', multiline: true },
    { key: 'solution', label: 'Proposed System Solution', multiline: true },
    { key: 'timeline', label: 'Estimated Project Timeline' },
    { key: 'pricing', label: 'Pricing Summary' },
    { key: 'nextSteps', label: 'Call to Action / Next Steps', multiline: true },
  ];

  return (
    <div className="space-y-6">
      <div className="space-y-2 flex items-start justify-between gap-4 flex-wrap">
        <div className="space-y-1.5">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#0058be]/8 text-[#0058be] text-[10px] font-bold uppercase tracking-widest mb-1">
            Step 7 of 8
          </span>
          <h2 className="text-3xl font-bold text-[#0b1c30] mb-2">Write Your Proposal Summary</h2>
          <p className="text-neutral-500 text-sm leading-relaxed">
            Summarise your offer parameters into client-facing text. Fields are pre-filled based on your inputs.
          </p>
        </div>

        {pool && (
          <button
            onClick={regenerateVariant}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-neutral-200 bg-white text-[10px] font-bold text-neutral-500 hover:text-neutral-700 hover:bg-neutral-50 transition-colors shadow-sm cursor-pointer select-none mt-1"
          >
            <Shuffle size={10} />
            Shuffle Copy
          </button>
        )}
      </div>

      {/* Inputs canvas layout */}
      <div className="space-y-4">
        {stringFields.map((field) => (
          <div key={field.key} className="space-y-1.5">
            <span className="block text-[10px] font-bold uppercase tracking-wider text-neutral-450">{field.label}</span>
            {field.multiline ? (
              <textarea
                value={proposalSummary[field.key]}
                onChange={(e) => update(field.key, e.target.value)}
                placeholder={placeholders[field.key]}
                rows={3}
                className="w-full px-4 py-3 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors resize-none leading-relaxed"
              />
            ) : (
              <input
                type="text"
                value={proposalSummary[field.key]}
                onChange={(e) => update(field.key, e.target.value)}
                placeholder={placeholders[field.key]}
                className="w-full h-10 px-4 rounded-xl outline-none text-xs text-[#0b1c30] placeholder:text-neutral-400 bg-white border border-neutral-200 focus:border-[#0058be] focus:ring-1 focus:ring-[#0058be] transition-colors"
              />
            )}
          </div>
        ))}

        {/* Deliverables summary */}
        <div className="space-y-2 pt-4 border-t border-neutral-200">
          <span className="block text-[10px] font-bold uppercase tracking-wider text-neutral-450">Deliverables Attached</span>
          <div className="flex flex-wrap gap-1.5">
            {deliverables.length > 0 ? deliverables.map((d, i) => (
              <span key={i} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#eff4ff]/60 border border-[#eff4ff] text-xs font-semibold text-[#0058be]">
                <Package size={12} className="text-[#0058be]" />
                {d}
              </span>
            )) : (
              <span className="text-xs text-neutral-450 italic">No deliverables scoped yet</span>
            )}
          </div>
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex items-center justify-between pt-4 border-t border-neutral-200">
        <span className="text-xs text-neutral-400">
          {isEmpty ? 'Complete all fields to continue' : 'Proposal details ready'}
        </span>

        <button
          onClick={nextStep}
          disabled={isEmpty}
          className={cn(
            'inline-flex items-center gap-1.5 px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-all cursor-pointer select-none border shadow-sm',
            !isEmpty
              ? 'bg-[#0058be] hover:bg-[#0047a0] text-white border-transparent'
              : 'bg-neutral-50 border-neutral-200 text-neutral-400 cursor-not-allowed',
          )}
        >
          Generate Blueprint
        </button>
      </div>
    </div>
  );
}
