import React, { useMemo, useEffect, useState, useCallback, useRef } from 'react';
import { Package, Shuffle, ArrowRight } from 'lucide-react';
import { useOfferEngineeringStore, useModule2ResolvedContent } from '../../lib/offer-engineering';
import { cn } from '../../lib/utils';
import { getServiceCategory, getAudienceLabel, generateProposalVariations } from '../../lib/blueprint-content';

type StringField = 'headline' | 'problem' | 'solution' | 'timeline' | 'pricing' | 'nextSteps';

interface VariantPool {
  headlines: string[];
  problems: string[];
  solutions: string[];
  nextSteps: string[];
}

function getVariationPool(cat: 'video' | 'wordpress' | 'design', niche: string): VariantPool {
  return generateProposalVariations(cat, '', '', '', '', niche);
}

const AutoResizingTextarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement>>((props, ref) => {
  const internalRef = useRef<HTMLTextAreaElement>(null);
  
  React.useImperativeHandle(ref, () => internalRef.current as HTMLTextAreaElement);

  useEffect(() => {
    const el = internalRef.current;
    if (el) {
      el.style.height = 'auto';
      el.style.height = el.scrollHeight + 'px';
    }
  }, [props.value]);

  return (
    <textarea
      ref={internalRef}
      {...props}
      onChange={(e) => {
        const el = e.target;
        el.style.height = 'auto';
        el.style.height = el.scrollHeight + 'px';
        props.onChange?.(e);
      }}
    />
  );
});
AutoResizingTextarea.displayName = 'AutoResizingTextarea';

export function ProposalSummaryStep() {
  const service = useOfferEngineeringStore((s) => s.service);
  const market = useOfferEngineeringStore((s) => s.market);
  const niche = useOfferEngineeringStore((s) => s.niche);
  const deliverables = useOfferEngineeringStore((s) => s.deliverables);
  const uniqueMechanism = useOfferEngineeringStore((s) => s.uniqueMechanism);
  const scopeLimits = useOfferEngineeringStore((s) => s.scopeLimits);
  const pricingModel = useOfferEngineeringStore((s) => s.pricingModel);
  const finalPrice = useOfferEngineeringStore((s) => s.finalPrice);
  const tieredPricing = useOfferEngineeringStore((s) => s.tieredPricing);
  const offerType = useOfferEngineeringStore((s) => s.offerType);
  const proposalSummary = useOfferEngineeringStore((s) => s.proposalSummary);
  const setProposalSummary = useOfferEngineeringStore((s) => s.setProposalSummary);
  const nextStep = useOfferEngineeringStore((s) => s.nextStep);
  const jumpToStep = useOfferEngineeringStore((s) => s.jumpToStep);
  
  const [variantIndex, setVariantIndex] = useState(0);
  const baselines = useRef<Record<string, string>>({});

  const { pathContent, engineeringData, serviceId } = useModule2ResolvedContent();

  const proposalAngle = pathContent?.content.proposalAngle;

  const cat = getServiceCategory(serviceId);
  const audience = getAudienceLabel(niche || '', market || '');
  const serviceLabel = engineeringData?.label ?? service ?? 'Your Service';

  const offerTypeLabel = offerType || 'one_time_project';

  const modelLabel =
    pricingModel === 'flat_rate' ? 'Flat Rate'
      : pricingModel === 'tiered' ? 'Tiered'
      : pricingModel === 'value_based' ? 'Value Based'
      : 'Custom';

  const pricingDesc = pricingModel === 'tiered'
    ? `$${tieredPricing.starterPrice}–$${tieredPricing.premiumPrice} (${modelLabel})`
    : finalPrice ? `$${finalPrice} (${modelLabel})` : `${modelLabel}`;

  const pool = getVariationPool(cat, niche);
  const varCount = pool
    ? Math.max(1, pool.headlines.length, pool.problems.length, pool.solutions.length, pool.nextSteps.length)
    : 1;
  const vi = variantIndex % varCount;

  const pickVar = useCallback(<T,>(arr: T[], idx: number, fallback: T): T => {
    return arr.length > 0 ? arr[idx % arr.length] : fallback;
  }, []);

  const autoGenerated = useMemo(() => {
    const fullPool = generateProposalVariations(cat, audience, serviceLabel, offerTypeLabel, uniqueMechanism || '', niche);
    return {
      headline: proposalAngle?.headline || pickVar(fullPool.headlines, vi, `${serviceLabel} for ${audience}`),
      problem: proposalAngle?.problem || pickVar(fullPool.problems, vi, `${audience} need a better approach to ${serviceLabel.toLowerCase()}.`),
      solution: proposalAngle?.solution || pickVar(fullPool.solutions, vi, `This package delivers ${deliverables.length > 0 ? deliverables.slice(0, 3).join(', ') + ', and more' : 'a complete service'}${uniqueMechanism ? ` using ${uniqueMechanism}` : ''}.`),
      timeline: scopeLimits.deliveryTime || 'Ongoing per agreed schedule',
      pricing: pricingDesc,
      nextSteps: proposalAngle?.nextStep || pickVar(fullPool.nextSteps, vi, `Schedule a short discovery call to discuss your goals and customise this package.`),
    };
  }, [cat, audience, serviceLabel, offerTypeLabel, uniqueMechanism, niche, vi, pickVar, deliverables, scopeLimits.deliveryTime, pricingDesc, proposalAngle]);

  useEffect(() => {
    const ps = proposalSummary;
    const updates: Partial<typeof ps> = {};
    if (!ps.headline.trim()) updates.headline = autoGenerated.headline;
    if (!ps.problem.trim()) updates.problem = autoGenerated.problem;
    if (!ps.solution.trim()) updates.solution = autoGenerated.solution;
    if (!ps.timeline.trim()) updates.timeline = autoGenerated.timeline;
    if (!ps.pricing.trim()) updates.pricing = autoGenerated.pricing;
    if (!ps.nextSteps.trim()) updates.nextSteps = autoGenerated.nextSteps;
    
    baselines.current = {
      headline: autoGenerated.headline,
      problem: autoGenerated.problem,
      solution: autoGenerated.solution,
      timeline: autoGenerated.timeline,
      pricing: autoGenerated.pricing,
      nextSteps: autoGenerated.nextSteps,
    };
    
    if (Object.keys(updates).length > 0) {
      setProposalSummary({ ...ps, ...updates });
    }
  }, [autoGenerated, proposalSummary, setProposalSummary]);

  const regenerateVariant = useCallback(() => {
    const nextIdx = (variantIndex + 1) % varCount;
    setVariantIndex(nextIdx);
    const ps = proposalSummary;
    const gen: Partial<typeof ps> = {};
    const newBaselines: Record<string, string> = { ...baselines.current };

    const shouldRegenerate = (field: string, newValue: string): boolean => {
      const current = (ps as any)[field] || '';
      const baseline = baselines.current[field] || '';
      return current.trim().length === 0 || current === baseline;
    };

    const h = proposalAngle?.headline || (pool ? pickVar(pool.headlines, nextIdx, autoGenerated.headline) : autoGenerated.headline);
    if (shouldRegenerate('headline', h)) { gen.headline = h; newBaselines.headline = h; }

    const p = proposalAngle?.problem || (pool ? pickVar(pool.problems, nextIdx, autoGenerated.problem) : autoGenerated.problem);
    if (shouldRegenerate('problem', p)) { gen.problem = p; newBaselines.problem = p; }

    const s = proposalAngle?.solution || (pool ? pickVar(pool.solutions, nextIdx, autoGenerated.solution) : autoGenerated.solution);
    if (shouldRegenerate('solution', s)) { gen.solution = s; newBaselines.solution = s; }

    if (shouldRegenerate('timeline', autoGenerated.timeline)) { gen.timeline = autoGenerated.timeline; newBaselines.timeline = autoGenerated.timeline; }

    if (shouldRegenerate('pricing', autoGenerated.pricing)) { gen.pricing = autoGenerated.pricing; newBaselines.pricing = autoGenerated.pricing; }

    const n = proposalAngle?.nextStep || (pool ? pickVar(pool.nextSteps, nextIdx, autoGenerated.nextSteps) : autoGenerated.nextSteps);
    if (shouldRegenerate('nextSteps', n)) { gen.nextSteps = n; newBaselines.nextSteps = n; }

    baselines.current = newBaselines;
    if (Object.keys(gen).length > 0) {
      setProposalSummary({ ...ps, ...gen });
    }
  }, [variantIndex, varCount, pool, pickVar, autoGenerated, proposalSummary, setProposalSummary, proposalAngle]);

  const update = (field: StringField, value: string) => {
    setProposalSummary({ ...proposalSummary, [field]: value });
  };

  const isEmpty =
    proposalSummary.headline.trim().length === 0 ||
    proposalSummary.problem.trim().length === 0 ||
    proposalSummary.solution.trim().length === 0 ||
    proposalSummary.timeline.trim().length === 0 ||
    proposalSummary.pricing.trim().length === 0 ||
    proposalSummary.nextSteps.trim().length === 0;

  const missingDeliverables = deliverables.length === 0;
  const isValid = !isEmpty && !missingDeliverables;

  return (
    <div className="space-y-6 max-w-4xl mx-auto pb-8">
      {/* Header Section */}
      <div className="space-y-4">
        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-[#0058be]/10 text-[#0058be] text-[10px] font-bold uppercase tracking-widest">
          PROPOSAL READY
        </span>
        
        <AutoResizingTextarea
          value={proposalSummary.headline}
          onChange={(e) => update('headline', e.target.value)}
          className="w-full text-3xl md:text-4xl font-bold text-[#0b1c30] outline-none bg-transparent placeholder:text-neutral-300 resize-none overflow-hidden"
          placeholder="Enter Proposal Headline"
          rows={1}
        />
        
        <p className="text-neutral-500 text-sm">
          Review and refine the copy before generating your offer blueprint.
        </p>
      </div>

      {/* Main Content Cards */}
      <div className="space-y-4">
        {/* Problem & Solution Container */}
        <div className="bg-white border border-neutral-200 rounded-xl overflow-hidden shadow-sm">
          <div className="p-4 md:p-5 border-b border-neutral-100 space-y-2">
            <label className="block text-[10px] font-bold uppercase tracking-wider text-neutral-400">1. The Problem</label>
            <AutoResizingTextarea
               value={proposalSummary.problem}
               onChange={(e) => update('problem', e.target.value)}
               className="w-full text-sm text-[#0b1c30] outline-none bg-transparent resize-none overflow-hidden placeholder:text-neutral-300 leading-relaxed min-h-[60px]"
               rows={2}
            />
          </div>
          <div className="p-4 md:p-5 bg-neutral-50/50 space-y-2">
            <label className="block text-[10px] font-bold uppercase tracking-wider text-neutral-400">2. The Solution</label>
            <AutoResizingTextarea
               value={proposalSummary.solution}
               onChange={(e) => update('solution', e.target.value)}
               className="w-full text-sm text-[#0b1c30] outline-none bg-transparent resize-none overflow-hidden placeholder:text-neutral-300 leading-relaxed min-h-[60px]"
               rows={2}
            />
          </div>
        </div>

        {/* Timeline & Pricing */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white border border-neutral-200 rounded-xl p-4 md:p-5 shadow-sm space-y-2">
            <label className="block text-[10px] font-bold uppercase tracking-wider text-neutral-400">3. Estimated Timeline</label>
            <input
               type="text"
               value={proposalSummary.timeline}
               onChange={(e) => update('timeline', e.target.value)}
               className="w-full text-sm text-[#0b1c30] font-medium outline-none bg-transparent placeholder:text-neutral-300"
               placeholder="e.g. 2-4 weeks"
            />
          </div>
          <div className="bg-white border border-neutral-200 rounded-xl p-4 md:p-5 shadow-sm space-y-2">
            <label className="block text-[10px] font-bold uppercase tracking-wider text-neutral-400">Pricing Summary</label>
            <input
               type="text"
               value={proposalSummary.pricing}
               onChange={(e) => update('pricing', e.target.value)}
               placeholder="TBD / Custom"
               className="w-full text-sm text-[#0b1c30] font-medium outline-none bg-transparent placeholder:text-neutral-300"
            />
          </div>
        </div>

        {/* Next Step (Call to Action) */}
        <div className="bg-[#eff4ff] border border-[#d6e4ff] rounded-xl p-4 md:p-5 shadow-sm space-y-3">
          <label className="block text-[10px] font-bold uppercase tracking-wider text-[#0058be]">4. Next Step</label>
          <AutoResizingTextarea
             value={proposalSummary.nextSteps}
             onChange={(e) => update('nextSteps', e.target.value)}
             className="w-full text-lg md:text-xl font-semibold text-[#0047a0] outline-none bg-transparent resize-none overflow-hidden placeholder:text-[#0058be]/50 leading-snug"
             rows={2}
          />
        </div>

        {/* Deliverables Included */}
        <div className="bg-white border border-neutral-200 rounded-xl p-4 md:p-5 shadow-sm space-y-3">
          <label className="block text-[10px] font-bold uppercase tracking-wider text-neutral-400">5. Deliverables Included</label>
          
          {deliverables.length > 0 ? (
            <div className="flex flex-col gap-2.5">
               {deliverables.map((d, i) => (
                 <div key={i} className="flex items-start gap-2.5 text-sm text-[#0b1c30]">
                   <span className="text-neutral-400 font-mono text-xs mt-0.5 min-w-[20px]">{i + 1}.</span>
                   <span className="leading-snug">{d}</span>
                 </div>
               ))}
            </div>
          ) : (
            <div className="rounded-lg bg-amber-50 border border-amber-200 p-4 flex flex-col md:flex-row md:items-center justify-between gap-3">
              <div className="flex items-center gap-2 text-amber-800">
                <Package size={16} />
                <span className="text-sm font-medium">No deliverables selected — return to Step 2</span>
              </div>
              <button 
                onClick={() => jumpToStep('deliverables')}
                className="px-4 py-2 bg-white border border-amber-200 text-amber-800 hover:bg-amber-100 transition-colors text-xs font-bold rounded-lg shadow-sm w-full md:w-auto"
              >
                Back to Deliverables
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex flex-col-reverse md:flex-row md:items-center justify-between gap-4 pt-6 mt-6 border-t border-neutral-200">
        <div className="flex flex-col md:flex-row md:items-center gap-4 w-full md:w-auto">
          {isValid ? (
            <span className="hidden md:inline-block text-xs font-bold uppercase tracking-wider text-emerald-600">
              ✓ Proposal ready
            </span>
          ) : (
            <span className="hidden md:inline-block text-xs text-neutral-400 uppercase tracking-wider font-bold">
              Incomplete fields
            </span>
          )}
          
          {pool && (
            <button
              onClick={regenerateVariant}
              className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-neutral-200 bg-white text-xs font-bold text-[#0b1c30] hover:bg-neutral-50 transition-colors shadow-sm w-full md:w-auto"
            >
              <Shuffle size={14} />
              Refresh Suggested Copy
            </button>
          )}
        </div>
        
        <div className="flex items-center w-full md:w-auto">
          <button
            onClick={nextStep}
            disabled={!isValid}
            className={cn(
              'w-full md:w-auto inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-sm',
              isValid
                ? 'bg-[#0058be] hover:bg-[#0047a0] text-white'
                : 'bg-neutral-100 text-neutral-400 cursor-not-allowed border border-neutral-200',
            )}
          >
            Generate Blueprint
            <ArrowRight size={14} />
          </button>
        </div>
      </div>
    </div>
  );
}
