import { useMemo, useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { Check, Copy, FileText, Download, ArrowRight } from 'lucide-react';
import { usePortfolioSystemStore } from '../../lib/portfolio-system';
import type { PortfolioReport } from '../../types/portfolio-system';
import { GOAL_OPTIONS, ASSET_LABEL_MAP, capitalize, toTitleCaseLabel } from '../../lib/blueprint-content';

function goalLabel(id: string): string {
  const found = GOAL_OPTIONS.find((o) => o.id === id);
  return found?.label ?? id.replace(/_/g, ' ');
}

function buildMarkdown(report: PortfolioReport): string {
  const lines: string[] = [
    '# Portfolio System Report',
    '',
    '---',
    '',
    '## 1. Portfolio Goal',
    '',
    report.goal.statement || '—',
    ...(report.goal.goals.length > 0 ? [
      '',
      '**Selected Goals:**',
      ...report.goal.goals.map((g) => `- ${goalLabel(g)}`),
    ] : []),
    '',
    '---',
    '',
    '## 2. Selected Portfolio Assets',
    '',
    ...report.selectedAssetTypes.map((t) => `- ${toTitleCaseLabel(t)}`),
    '',
    '---',
    '',
    '## 3. Case Study',
    '',
    `**Project:** ${report.caseStudy.projectTitle || '—'}`,
    `**Client/Niche:** ${report.caseStudy.clientNicheType || '—'}`,
    report.caseStudy.isSampleProject ? '*This is a sample project.*' : '',
    '',
    `**Problem:** ${report.caseStudy.problem || '—'}`,
    `**Process:** ${report.caseStudy.process || '—'}`,
    `**Deliverables:** ${report.caseStudy.deliverables || '—'}`,
    `**Result:** ${report.caseStudy.resultExpectedOutcome || '—'}`,
    `**Tools:** ${report.caseStudy.toolsUsed || '—'}`,
    `**CTA:** ${report.caseStudy.cta || '—'}`,
    '',
    '---',
    '',
    '## 4. Sample Project',
    '',
    `**Name:** ${report.sampleProject.projectName || '—'}`,
    `**Goal:** ${report.sampleProject.goal || '—'}`,
    `**What to Create:** ${report.sampleProject.whatToCreate || '—'}`,
    '',
    '**Deliverables:**',
    ...report.sampleProject.deliverables.map((d) => `- ${d}`),
    '',
    `**Timeline:** ${report.sampleProject.timeline || '—'}`,
    `**How to Present:** ${report.sampleProject.howToPresent || '—'}`,
    '',
    '---',
    '',
    '## 5. Portfolio Page Outline',
    '',
    ...report.pageStructure.sections
      .filter((s) => s.included)
      .map((s) => `- **${s.label}:** ${s.description}`),
    '',
    '---',
    '',
    '## 6. Portfolio Copy',
    '',
    `**Headline:** ${report.copy.headline || '—'}`,
    '',
    `**Short Intro:** ${report.copy.shortIntro || '—'}`,
    '',
    `**Case Study Intro:** ${report.copy.caseStudyIntro || '—'}`,
    '',
    `**Process:** ${report.copy.processSection || '—'}`,
    '',
    `**CTA:** ${report.copy.cta || '—'}`,
    '',
    '---',
    '',
    '## 7. Portfolio Checklist',
    '',
    ...report.checklist.map((item) =>
      `- [${item.status === 'ready' ? 'x' : ' '}] **${item.label}** (${capitalize(item.status)})`
    ),
    '',
    '---',
    '',
    '## 8. Next Actions',
    '',
    ...report.nextActions.map((a, i) => `${i + 1}. ${a}`),
    '',
    '---',
    '',
    '*Generated by Portfolio System — Phase 4 of Client Acquisition System*',
    '',
  ];
  return lines.join('\n');
}

function buildNextActions(cat: 'video' | 'wordpress' | 'design'): string[] {
  const perCategory: Record<string, string[]> = {
    video: [
      'Create one sample gaming shorts pack from your own footage.',
      'Record a short before/after editing breakdown showing pacing and hook changes.',
      'Publish the sample pack on your portfolio page with a note explaining your editing decisions.',
      'Add your editing process and delivery timeline to the portfolio page.',
      'Share the portfolio link with 10 gaming creators or communities.',
      'Update the portfolio after every new sample or client project.',
    ],
    wordpress: [
      'Create one sample website build for a fictional startup.',
      'Record a performance comparison (Lighthouse scores before/after optimisation).',
      'Publish the sample site on your portfolio page with a write-up of the build decisions.',
      'Add your build process and delivery timeline to the portfolio page.',
      'Share the portfolio link with 10 startup founders or founders in online communities.',
      'Update the portfolio after every new project.',
    ],
    design: [
      'Create one sample UI redesign concept for a real product you use.',
      'Record a before/after walkthrough explaining the design decisions and impact.',
      'Publish the case study on your portfolio page with screenshots and a link to the Figma prototype.',
      'Add your design process and delivery timeline to the portfolio page.',
      'Share the portfolio link with 10 product teams or design communities.',
      'Update the portfolio after every new project.',
    ],
  };
  return perCategory[cat] || perCategory.video;
}

const VIDEO_SERVICES = ['short_form_clips', 'long_form_content', 'podcast_post_production'];
const WP_SERVICES = ['custom_theme_development', 'plugin_integration_dev', 'site_migration_performance'];
const DESIGN_SERVICES = ['product_ui_design', 'brand_identity_visual_systems', 'ux_research_conversion_audits'];

function category(service: string | null): 'video' | 'wordpress' | 'design' {
  if (!service) return 'video';
  if (VIDEO_SERVICES.includes(service)) return 'video';
  if (WP_SERVICES.includes(service)) return 'wordpress';
  if (DESIGN_SERVICES.includes(service)) return 'design';
  return 'video';
}

export function PortfolioReportStep() {
  const goal = usePortfolioSystemStore((s) => s.portfolioGoal);
  const selectedAssetTypes = usePortfolioSystemStore((s) => s.selectedAssetTypes);
  const caseStudy = usePortfolioSystemStore((s) => s.caseStudy);
  const sampleProject = usePortfolioSystemStore((s) => s.sampleProject);
  const pageStructure = usePortfolioSystemStore((s) => s.pageStructure);
  const portfolioCopy = usePortfolioSystemStore((s) => s.portfolioCopy);
  const checklist = usePortfolioSystemStore((s) => s.checklist) ?? [];
  const report = usePortfolioSystemStore((s) => s.portfolioReport);
  const setReport = usePortfolioSystemStore((s) => s.setPortfolioReport);
  const confirmStep = usePortfolioSystemStore((s) => s.confirmStep);
  const isCompleted = usePortfolioSystemStore((s) => s.completedSteps).includes('portfolio_report');
  const service = usePortfolioSystemStore((s) => s.phase3Service);
  const offerName = usePortfolioSystemStore((s) => s.phase3OfferName) ?? '';
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();
  const cat = category(service);

  const downloadSlug = offerName
    ? offerName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '-portfolio-report.md'
    : 'portfolio-system-report.md';

  const generatedReport = useMemo((): PortfolioReport => {
    if (report) return report;
    return {
      goal,
      selectedAssetTypes,
      caseStudy,
      sampleProject,
      pageStructure,
      copy: portfolioCopy,
      checklist,
      nextActions: buildNextActions(cat),
    };
  }, [report, goal, selectedAssetTypes, caseStudy, sampleProject, pageStructure, portfolioCopy, checklist, cat]);

  const handleGenerate = () => {
    setReport(generatedReport);
    confirmStep();
  };

  const handleCopy = useCallback(async () => {
    const markdown = buildMarkdown(generatedReport);
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = markdown;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }, [generatedReport]);

  const handleDownload = useCallback(() => {
    const markdown = buildMarkdown(generatedReport);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = downloadSlug;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generatedReport]);

  if (!report) {
    return (
      <div className="space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-zinc-500">Step 8 of 8</span>
          <h2 className="text-2xl font-bold tracking-tight text-white/95">Generate Portfolio Report</h2>
          <p className="text-sm text-zinc-400 max-w-lg">
            Compile everything into a final portfolio system report.
          </p>
        </div>

        <div className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <FileText size={14} className="text-zinc-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="text-xs text-white/80 leading-relaxed">
              Review all sections and generate the final report. Once generated, you can copy or download as Markdown.
            </p>
          </div>
        </div>

        <ReportPreview report={generatedReport} />

        <motion.button
          onClick={handleGenerate}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-6 h-11 rounded-lg text-xs font-bold uppercase tracking-[0.08em] bg-white text-black hover:bg-white/90 shadow-[0_0_30px_-12px_rgba(255,255,255,0.15)] transition-all duration-300 cursor-pointer"
        >
          <Download size={14} />
          Generate Portfolio Report
        </motion.button>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <span className="text-[10px] font-bold uppercase tracking-[0.15em] text-emerald-400">Step 8 of 8 — Complete</span>
        <h2 className="text-2xl font-bold tracking-tight text-white/95">Portfolio Report Generated</h2>
        <p className="text-sm text-zinc-400 max-w-lg">
          Your portfolio system is ready. Copy or download the report for reference.
        </p>
      </div>

      <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20">
        <Check size={14} className="text-emerald-400 shrink-0" />
        <span className="text-xs font-medium text-emerald-400">
          Portfolio system complete — all 8 steps finished
        </span>
      </div>

      <ReportPreview report={generatedReport} />

      <div className="flex items-center gap-3 pt-2 flex-wrap">
        <motion.button
          onClick={handleCopy}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <Copy size={12} />
          {copied ? 'Copied!' : 'Copy Report'}
        </motion.button>

        <motion.button
          onClick={handleDownload}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-white/[0.03] border border-white/5 text-zinc-400 hover:bg-white/5 hover:text-zinc-300 transition-all duration-200 cursor-pointer"
        >
          <FileText size={12} />
          Download Markdown
        </motion.button>

        <motion.button
          onClick={() => navigate('/workspace/client-pipeline')}
          whileTap={{ scale: 0.97 }}
          className="inline-flex items-center gap-2 px-5 h-10 rounded-lg text-[10px] font-bold uppercase tracking-[0.08em] bg-brand-primary/10 border border-brand-primary/30 text-brand-primary hover:bg-brand-primary/15 transition-all duration-200 cursor-pointer"
        >
          <ArrowRight size={12} />
          Continue to Client Pipeline
        </motion.button>
      </div>
    </div>
  );
}

function ReportPreview({ report }: { report: PortfolioReport }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <div className="p-5 border-b border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <FileText size={14} className="text-brand-primary" />
          <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-brand-primary">Portfolio Report</p>
        </div>
        <p className="text-sm text-white/80 leading-relaxed">{report.goal.statement || '—'}</p>
        {report.goal.goals.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mt-2">
            {report.goal.goals.map((g, i) => (
              <span key={i} className="px-2 py-0.5 rounded bg-white/[0.04] border border-white/5 text-[9px] text-zinc-400">
                {goalLabel(g)}
              </span>
            ))}
          </div>
        )}
      </div>

      <div className="p-5 space-y-5 divide-y divide-white/[0.04]">
        <Section title="Selected Assets">
          {report.selectedAssetTypes.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {report.selectedAssetTypes.map((t, i) => (
                <span key={i} className="px-3 py-1.5 rounded-full bg-white/10 border border-white/10 text-[11px] font-medium text-white/80">
                  {toTitleCaseLabel(t)}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Case Study" className="pt-4">
          {report.caseStudy.projectTitle ? (
            <div className="space-y-2">
              <p className="text-xs font-semibold text-white/80">{report.caseStudy.projectTitle}</p>
              <p className="text-[9px] text-zinc-500">{report.caseStudy.clientNicheType}</p>
              <p className="text-xs text-zinc-400">{report.caseStudy.problem}</p>
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Sample Project" className="pt-4">
          {report.sampleProject.projectName ? (
            <div className="space-y-1">
              <p className="text-xs font-semibold text-white/80">{report.sampleProject.projectName}</p>
              <p className="text-[9px] text-zinc-400">{report.sampleProject.goal}</p>
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Page Outline" className="pt-4">
          {report.pageStructure.sections.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {report.pageStructure.sections.filter((s) => s.included).map((s) => (
                <span key={s.id} className="px-2 py-1 rounded bg-brand-primary/10 text-[9px] font-medium text-brand-primary">
                  {s.label}
                </span>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Portfolio Copy" className="pt-4">
          {report.copy.headline ? (
            <div className="space-y-1">
              <p className="text-xs text-white/80 font-medium">{report.copy.headline}</p>
              <p className="text-[9px] text-zinc-400">{report.copy.shortIntro}</p>
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Checklist" className="pt-4">
          {report.checklist.length > 0 ? (
            <div className="space-y-0.5">
              {report.checklist.map((item, i) => (
                <div key={i} className="flex items-center gap-2 text-[10px] text-zinc-400">
                  <span className={`w-3 h-3 rounded flex items-center justify-center text-[6px] font-bold ${
                    item.status === 'ready' ? 'bg-emerald-500/20 text-emerald-400' :
                    item.status === 'in_progress' ? 'bg-amber-400/10 text-amber-400' :
                    'bg-zinc-500/20 text-zinc-500'
                  }`}>
                    {item.status === 'ready' ? '✓' : item.status === 'in_progress' ? '…' : '○'}
                  </span>
                  {item.label}
                </div>
              ))}
            </div>
          ) : <Empty />}
        </Section>

        <Section title="Next Actions" className="pt-4">
          <ul className="space-y-1.5">
            {report.nextActions.map((action, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-white/70">
                <span className="flex items-center justify-center w-4 h-4 rounded-full bg-brand-primary/15 text-[8px] font-bold text-brand-primary shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {action}
              </li>
            ))}
          </ul>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children, className }: { title: string; children: React.ReactNode; className?: string }) {
  return (
    <div className={className || ''}>
      <p className="text-[9px] font-bold uppercase tracking-[0.15em] text-zinc-500 mb-2">{title}</p>
      {children}
    </div>
  );
}

function Empty() {
  return <p className="text-sm text-zinc-500">—</p>;
}
